"""Build tc3_data.js — a static, offline data bundle for the TC3 Tool Optimizer.

Source: local TConstruct 3.11.2 source tree (tc_src) — identical to the
TConstruct-1.20.1-3.11.2.166.jar datapack shipped by CABIN 2.1.3.
Availability: evaluated against CABIN 2.1.3's actual mod list
(pakku-lock.json: Thermal Series + Create present; Mekanism / Immersive
Engineering / Twilight Forest absent) and CABIN's own KubeJS scripts
(custom pewter alloy: lead + glass).

Usage:  python build_tc3_data.py <tc_src_dir> <out_js>
"""
import json, os, sys, datetime

TC_SRC, OUT = sys.argv[1], sys.argv[2]

GEN = os.path.join(TC_SRC, 'src/generated/resources/data/tconstruct')
TC = 'src/generated/resources/data/tconstruct/tinkering/'
MOD_RECIPE_BASE = 'src/generated/resources/data/tconstruct/recipes/tools/modifiers/'
LANG_PATH = 'src/main/resources/assets/tconstruct/lang/en_us.json'

DIRS = [
    TC + 'materials/stats',
    TC + 'materials/traits',
    TC + 'tool_definitions',
    TC + 'materials/definition',
    MOD_RECIPE_BASE + 'upgrade',
    MOD_RECIPE_BASE + 'ability',
    MOD_RECIPE_BASE + 'defense',
    TC + 'modifiers',
]

dirs, files = {}, {}
for d in DIRS:
    local = os.path.join(TC_SRC, d.replace('/', os.sep))
    names = sorted(f[:-5] for f in os.listdir(local) if f.endswith('.json'))
    dirs[d] = names
    for n in names:
        p = f'{d}/{n}.json'
        with open(os.path.join(local, n + '.json'), encoding='utf-8') as fh:
            files[p] = json.load(fh)

# lang: only the keys the optimizer actually looks up
with open(os.path.join(TC_SRC, LANG_PATH.replace('/', os.sep)), encoding='utf-8') as fh:
    lang_full = json.load(fh)
lang = {k: v for k, v in lang_full.items()
        if k.startswith('material.tconstruct.') or k.startswith('modifier.tconstruct.')}
files[LANG_PATH] = lang

# ── CABIN 2.1.3 availability ─────────────────────────────────────
# Integration materials the pack actually provides (Thermal ingots,
# Create zinc/copper context, KubeJS pewter alloy recipe).
CABIN_AVAILABLE = [
    'constantan', 'electrum', 'invar',          # Thermal Series
    'bronze', 'lead', 'silver',                 # common metals present in pack
    'pewter',                                   # CABIN custom alloy (lead + glass)
]
# Integration materials with no source in CABIN (missing mods).
CABIN_UNAVAILABLE = [
    'aluminum', 'osmium', 'necronium',          # no Mekanism / no aluminum source
    'fiery', 'ironwood', 'steeleaf',            # no Twilight Forest
    'treated_wood',                             # no Immersive Engineering
    'plated_slimewood', 'nicrosil',             # no providing mod (nicrosil has no 3.11 def anyway)
]
# Mods-panel groups that match CABIN's mod list (used only when the user
# has no saved preference).
CABIN_DEFAULT_INTEGRATIONS = ['thermal', 'common_metals']

bundle = {
    'meta': {
        'source': 'TConstruct 3.11.2.166 datapack (bundled in CABIN 2.1.3)',
        'built': datetime.date.today().isoformat(),
        'materials': len(dirs[TC + 'materials/stats']),
        'tools': len(dirs[TC + 'tool_definitions']),
    },
    'dirs': dirs,
    'files': files,
    'cabin': {
        'available': CABIN_AVAILABLE,
        'unavailable': CABIN_UNAVAILABLE,
        'defaultIntegrations': CABIN_DEFAULT_INTEGRATIONS,
    },
}

with open(OUT, 'w', encoding='utf-8') as fh:
    fh.write('// GENERATED by build_tc3_data.py — do not edit. Re-run the script to refresh.\n')
    fh.write('window.TC3_DATA = ')
    json.dump(bundle, fh, ensure_ascii=False, separators=(',', ':'))
    fh.write(';\n')

print(f"wrote {OUT}: {os.path.getsize(OUT)/1024:.0f} KB, "
      f"{len(files)} files, {len(dirs)} dirs")
