// ═══════════════════════════════════════════════════════════════
// DATA SOURCE
// All datapack JSON is bundled statically in tc3_data.js
// (window.TC3_DATA), generated by build_tc3_data.py from the
// TConstruct 3.11.2.166 datapack shipped inside CABIN 2.1.3.
// Nothing game-affecting is fetched at runtime; the only network
// requests left are cosmetic icons. Re-run build_tc3_data.py after
// a CABIN update that bumps TConstruct.
// ═══════════════════════════════════════════════════════════════

const DATA = (typeof window !== 'undefined' ? window : globalThis).TC3_DATA;
if (!DATA && typeof document?.addEventListener === 'function') {
  document.addEventListener('DOMContentLoaded', () =>
    showError('tc3_data.js is missing — run build_tc3_data.py to generate the static data bundle.'));
}

const TC  = 'src/generated/resources/data/tconstruct/tinkering/';
const MOD_RECIPE_BASE = 'src/generated/resources/data/tconstruct/recipes/tools/modifiers/';
const LANG_PATH = 'src/main/resources/assets/tconstruct/lang/en_us.json';

// ─── Mapping: TC3 item ID → stat slot type ────────────────────
// Sourced from TC3 part item definitions
const ITEM_STAT = {
  // Head-type parts (provide: flat durability, melee_attack, mining_speed, mining_tier)
  'tconstruct:pick_head':       'head',
  'tconstruct:small_blade':     'head',
  'tconstruct:small_axe_head':  'head',
  'tconstruct:broad_axe_head':  'head',
  'tconstruct:hammer_head':     'head',
  'tconstruct:broad_blade':     'head',
  'tconstruct:adze_head':       'head',
  'tconstruct:large_plate':     'head',
  // Handle-type parts (provide: durability mult, melee_damage, melee_speed, mining_speed mult)
  'tconstruct:tool_handle':     'handle',
  'tconstruct:tough_handle':    'handle',
  // Binding-type parts (no stats, only traits)
  'tconstruct:tool_binding':    'binding',
  'tconstruct:tough_binding':   'binding',
  // Ranged/special parts
  'tconstruct:bow_limb':        'limb',
  'tconstruct:bow_grip':        'grip',
  'tconstruct:bowstring':       'bowstring',
  'tconstruct:shield_core':     'shield_core',
  // Armor plating parts
  'tconstruct:helmet_plating':      'plating_helmet',
  'tconstruct:chestplate_plating':  'plating_chestplate',
  'tconstruct:leggings_plating':    'plating_leggings',
  'tconstruct:boots_plating':       'plating_boots',
  'tconstruct:maille':              'maille',
};

// Mapping: tconstruct:material_stats stat_type → local slot type
const TC_STAT_TYPE = {
  'tconstruct:head':              'head',
  'tconstruct:handle':            'handle',
  'tconstruct:binding':           'binding',
  'tconstruct:limb':              'limb',
  'tconstruct:bowstring':         'bowstring',
  'tconstruct:grip':              'grip',
  'tconstruct:plating_helmet':    'plating_helmet',
  'tconstruct:plating_chestplate':'plating_chestplate',
  'tconstruct:plating_leggings':  'plating_leggings',
  'tconstruct:plating_boots':     'plating_boots',
  'tconstruct:plating_shield':    'plating_shield',
  'tconstruct:skull':             'skull',
  'tconstruct:maille':            'maille',
  'tconstruct:cuirass':           'cuirass',
};

// ─── Modifier definitions — populated dynamically in init() from GitHub ──────
// Fetched from recipes/tools/modifiers/{upgrade,ability}/ (slot+maxLevel)
// and tinkering/modifiers/{name}.json (effects, display name from lang).
let MODIFIER_DEFS = {};
let TRAIT_EFFECTS = {}; // traitId → [{ stat, op, flat?, eachLevel? }]

// Descriptions for traits whose effects can't be parsed as static stat_boost values.
// label: short text shown inside the trait pill (alongside the name)
// desc:  longer text shown in the custom hover tooltip
const TRAIT_KNOWN = {
  momentum:   { label: 'stackable MSpd',        desc: '+25% mining speed per level while mining continuously; resets when you stop' },
  dwarven:    { label: 'MSpd underground',       desc: 'Mining speed increases the deeper underground you are' },
  magnetic:   { label: 'auto-collects drops',    desc: 'Pulls mined item drops toward the player automatically' },
  overgrowth: { label: 'self-repairs in sun',    desc: 'Slowly repairs durability when exposed to direct sunlight' },
  cultivated: { label: 'repairs from plants',    desc: 'Repairs durability when harvesting plant-based items' },
  maintained: { label: 'skip dur use',           desc: 'Chance to avoid consuming durability on each use' },
  crude:      { label: '+MSpd natural blocks',   desc: 'Bonus mining speed against dirt, stone, and other natural blocks' },
  jagged:     { label: '+Atk as dur drops',      desc: 'Attack damage scales up as the tool loses durability' },
  tasty:      { label: 'edible',                 desc: 'The tool can be eaten as food in a pinch' },
  scorching:  { label: 'ignites targets',        desc: 'Sets struck targets on fire' },
  enhanced:   { label: '+MSpd in darkness',      desc: 'Mining speed increases in low-light conditions' },
  earthen:    { label: '+MSpd from armor',       desc: 'Mining speed bonus scales with the weight of armor worn' },
  insatiable: { label: 'Fortune scales',         desc: 'Fortune level increases with each consecutive use' },
  blasting:   { label: '+MSpd near explosions',  desc: 'Gains temporary mining speed bonus after nearby explosions' },
};

// ─── Mod integration groups ───────────────────────────────────
// Materials gated behind a `condition` in their def JSON — only present if
// the companion mod is installed. Users can opt-in through the settings panel.
const MOD_INTEGRATIONS = {
  twilight_forest:       { label: 'Twilight Forest',              materials: ['fiery','ironwood','steeleaf','pewter'] },
  thermal:               { label: 'Thermal Expansion / Series',   materials: ['constantan','electrum','invar'] },
  mekanism:              { label: 'Mekanism',                     materials: ['aluminum','osmium','necronium'] },
  immersive_engineering: { label: 'Immersive Engineering',        materials: ['treated_wood'] },
  common_metals:         { label: 'Common Metals (Bronze/Lead/Silver/Nicrosil)', materials: ['bronze','lead','silver','plated_slimewood','nicrosil'] },
  tc3_hidden:            { label: 'Drop-only materials (Ancient / Knightslime)', materials: ['ancient', 'knightslime'] },
};
// Reverse map: material name → mod key
const MAT_TO_MOD = {};
for (const [mod, { materials }] of Object.entries(MOD_INTEGRATIONS))
  for (const m of materials) MAT_TO_MOD[m] = mod;

// Parsed integration materials, not active until the user enables their mod
let CONDITIONAL_MATERIALS = {}; // name → mat

// ─── Mining tier ordering ─────────────────────────────────────
const TIERS = { wood:0, stone:1, gold:1, iron:2, diamond:3, netherite:4 };
const TIER_LABEL = {
  'minecraft:wood':'Wood','minecraft:stone':'Stone','minecraft:gold':'Gold',
  'minecraft:iron':'Iron','minecraft:diamond':'Diamond','minecraft:netherite':'Netherite'
};
const TIER_CLASS = {
  'minecraft:wood':'tier-wood','minecraft:stone':'tier-stone','minecraft:gold':'tier-gold',
  'minecraft:iron':'tier-iron','minecraft:diamond':'tier-diamond','minecraft:netherite':'tier-netherite'
};
const TIER_ABBREV = {
  'minecraft:wood':'W','minecraft:stone':'S','minecraft:gold':'G',
  'minecraft:iron':'I','minecraft:diamond':'D','minecraft:netherite':'N'
};
const _MC_ASSETS = 'https://raw.githubusercontent.com/InventivetalentDev/minecraft-assets/1.20.1/assets/minecraft/textures/';
const TIER_ICON = {
  'minecraft:wood':      _MC_ASSETS + 'block/oak_planks.png',
  'minecraft:stone':     _MC_ASSETS + 'block/cobblestone.png',
  'minecraft:gold':      _MC_ASSETS + 'item/gold_ingot.png',
  'minecraft:iron':      _MC_ASSETS + 'item/iron_ingot.png',
  'minecraft:diamond':   _MC_ASSETS + 'item/diamond.png',
  'minecraft:netherite': _MC_ASSETS + 'item/netherite_ingot.png',
};
const ARMOR_PLATING_TYPES = new Set(['plating_helmet','plating_chestplate','plating_leggings','plating_boots','plating_shield']);

// ─── Tool metadata: display name, icon, group, notes ─────────
const TOOL_ORDER = [
  'pickaxe','pickadze','excavator','sledge_hammer','vein_hammer',
  'dagger','sword','kama','hand_axe','mattock','broad_axe','cleaver','scythe',
  'minotaur_axe','war_pick','throwing_axe','javelin','battlesign',
  'earth_staff','sky_staff','ichor_staff','ender_staff',
  'plate_helmet','plate_chestplate','plate_leggings','plate_boots',
  'travelers_helmet','travelers_chestplate','travelers_leggings','travelers_boots',
];
const _TC_TOOL_ICON = 'https://raw.githubusercontent.com/SlimeKnights/TinkersConstruct/v3.11.2.166/src/main/resources/assets/tconstruct/textures/item/tool/';
const TOOL_META = {
  pickaxe:       { icon:'⛏',  iconUrl:_TC_TOOL_ICON+'pickaxe/head.png',      group:'Mining',  notes:'Standard pickaxe; no base AOE (box AOE expandable with upgrades); Pierce I trait' },
  pickadze:      { icon:'⛏',  iconUrl:_TC_TOOL_ICON+'pickadze/head.png',      group:'Mining',  notes:'Dual pickaxe + shovel; mining tier capped at Gold; expandable AOE; Pathing trait' },
  excavator:     { icon:'🪣',  iconUrl:_TC_TOOL_ICON+'excavator/head.png',     group:'Mining',  notes:'3×3 AOE shovel (expandable); Knockback II + Pathing traits; 2 upgrade slots' },
  sledge_hammer: { icon:'🔨',  iconUrl:_TC_TOOL_ICON+'sledge_hammer/head.png', group:'Mining',  notes:'3×3 AOE pickaxe (expandable); Smite II trait vs undead; 2 upgrade slots' },
  vein_hammer:   { icon:'💎',  iconUrl:_TC_TOOL_ICON+'vein_hammer/head.png',   group:'Mining',  notes:'Mines connected veins of matching blocks; max distance 2 (expandable); 2 upgrade slots' },
  dagger:        { icon:'🗡',  iconUrl:_TC_TOOL_ICON+'dagger/head.png',        group:'Melee',   notes:'Fastest attack speed (2.0); offhand capable; Padded I trait' },
  sword:         { icon:'⚔',  iconUrl:_MC_ASSETS+'item/iron_sword.png',       group:'Melee',   notes:'Sweep attack (1-block radius); blocks up to 10 damage; Silky Shears trait' },
  kama:          { icon:'🌾',  iconUrl:_TC_TOOL_ICON+'kama/head.png',          group:'Melee',   notes:'Tills, shears, and harvests crops; 3D circle AOE; heavily reduced melee damage' },
  hand_axe:      { icon:'🪓',  iconUrl:_TC_TOOL_ICON+'hand_axe/head.png',      group:'Melee',   notes:'Disables shields on hit; strips logs; expandable 2D circle AOE mining' },
  mattock:       { icon:'🪚',  iconUrl:_TC_TOOL_ICON+'mattock/head.png',       group:'Melee',   notes:'Dual axe + shovel; Tilling trait; mines only immediately adjacent blocks (not true vein)' },
  broad_axe:     { icon:'🪓',  iconUrl:_TC_TOOL_ICON+'broad_axe/head.png',     group:'Melee',   notes:'Fells whole trees (tree AOE); wide vertical AOE on non-trees; disables shields; 2 upgrade slots' },
  cleaver:       { icon:'🔪',  iconUrl:_TC_TOOL_ICON+'cleaver/head.png',       group:'Melee',   notes:'2-block sweep attack; Severing II (chance to behead); 2 upgrade slots' },
  scythe:        { icon:'⚙',  iconUrl:_TC_TOOL_ICON+'scythe/head.png',        group:'Melee',   notes:'3×3+ box AOE harvesting; 2-block circular melee; Tilling + Harvest traits; 2 upgrade slots' },
  minotaur_axe:  { icon:'🐂',  iconUrl:_TC_TOOL_ICON+'minotaur_axe/head.png', group:'Special', notes:'Two head slots (averaged stats); Charge Attack trait (sprint bonus damage); tall vertical AOE; 3 upgrade slots' },
  war_pick:      { icon:'⚔',  iconUrl:_TC_TOOL_ICON+'war_pick/head.png',      group:'Special', notes:'Hybrid melee+ranged pickaxe; War Charge trait (mining charges next ranged shot); 3 upgrade slots' },
  throwing_axe:  { icon:'🪓',  iconUrl:_TC_TOOL_ICON+'throwing_axe/head.png', group:'Special', notes:'Throwable ranged weapon; melee capable; no base AOE' },
  javelin:       { icon:'🗡',  iconUrl:_TC_TOOL_ICON+'javelin/head.png',       group:'Special', notes:'Melee + ranged hybrid; throwable; blocks up to 10 damage; 2 upgrade slots' },
  battlesign:    { icon:'🛡',  iconUrl:_TC_TOOL_ICON+'battlesign/head.png',    group:'Special', notes:'Melee + shield hybrid; blocks 50 damage (120° arc); uses defense slots (not upgrades)' },
  earth_staff:   { icon:'🪄', group:'Staffs', notes:'High defense (35 block amt, 140° angle); box AOE; Accuracy 0.9, Projectile Dmg 1.0; 2 upgrades, 3 defense, 2 abilities' },
  sky_staff:     { icon:'🪄', group:'Staffs', notes:'Most upgradable (5 upgrade slots); circle AOE; fastest draw speed (1.25×); lowest durability (500); 2 abilities' },
  ichor_staff:   { icon:'🪄', group:'Staffs', notes:'Most abilities (3 ability slots); vein AOE; high velocity (1.2×), slow draw (0.75×); 2 upgrades' },
  ender_staff:   { icon:'🪄', group:'Staffs', notes:'Highest durability (1520); box AOE; low accuracy (0.5), highest projectile dmg (3.0); Reach II; 3 upgrades, 1 defense, 2 abilities' },
  // Armor
  plate_helmet:       { icon:'🪖', iconUrl:_MC_ASSETS+'item/iron_helmet.png',      group:'Armor', notes:'Plate helmet; plating + maille slots; high armor from plating material' },
  plate_chestplate:   { icon:'🛡', iconUrl:_MC_ASSETS+'item/iron_chestplate.png',  group:'Armor', notes:'Plate chestplate; largest armor value; plating + maille slots' },
  plate_leggings:     { icon:'🦺', iconUrl:_MC_ASSETS+'item/iron_leggings.png',    group:'Armor', notes:'Plate leggings; plating + maille slots' },
  plate_boots:        { icon:'👢', iconUrl:_MC_ASSETS+'item/iron_boots.png',        group:'Armor', notes:'Plate boots; plating + maille slots' },
  travelers_helmet:     { icon:'🪖', iconUrl:_MC_ASSETS+'item/leather_helmet.png',    group:'Armor', notes:'Travelers helmet; plating (scaled) + maille slots' },
  travelers_chestplate: { icon:'🛡', iconUrl:_MC_ASSETS+'item/leather_chestplate.png',group:'Armor', notes:'Travelers chestplate; plating (scaled) + maille slots' },
  travelers_leggings:   { icon:'🦺', iconUrl:_MC_ASSETS+'item/leather_leggings.png',  group:'Armor', notes:'Travelers leggings; plating (scaled) + maille slots' },
  travelers_boots:      { icon:'👢', iconUrl:_MC_ASSETS+'item/leather_boots.png',     group:'Armor', notes:'Travelers boots; plating (scaled) + maille slots' },
};

// ─── Default optimizer goal per tool ─────────────────────────
const TOOL_DEFAULT_GOAL = {
  // Mining tools → prioritise mining speed
  pickaxe:      'mining', pickadze:  'mining', excavator:    'mining',
  sledge_hammer:'mining', vein_hammer:'mining', war_pick:    'mining',
  // Melee tools → DPS
  dagger:'dps', sword:'dps', hand_axe:'dps', mattock:'dps',
  broad_axe:'dps', cleaver:'dps', minotaur_axe:'dps',
  // Utility hybrids → balanced
  kama:'balanced', scythe:'balanced', mattock:'balanced',
  // Ranged / special → damage
  throwing_axe:'damage', javelin:'damage', battlesign:'durability',
  // Armor → defense
  plate_helmet:'defense', plate_chestplate:'defense', plate_leggings:'defense', plate_boots:'defense',
  travelers_helmet:'defense', travelers_chestplate:'defense', travelers_leggings:'defense', travelers_boots:'defense',
};

// ═══════════════════════════════════════════════════════════════
// STATE
// ═══════════════════════════════════════════════════════════════
let MATERIALS = {};
let TOOLS     = {};
let currentTool       = '';
let currentGroup      = '';
let selectedMaterials = {};
let selectedModifiers = {}; // { modKey: level, ... }

// ═══════════════════════════════════════════════════════════════
// UTILITIES
// ═══════════════════════════════════════════════════════════════
function toTitleCase(s) { return s.replace(/\b\w/g, c => c.toUpperCase()); }
function toRoman(n) { return ['','I','II','III','IV','V','VI','VII','VIII','IX','X'][n] || String(n); }

function itemLabel(item) {
  return toTitleCase(item.replace(/^.*:/, '').replace(/_/g, ' '));
}
function statTypeLabel(st) {
  const map = {
    'tconstruct:head':'Head','tconstruct:handle':'Handle','tconstruct:binding':'Binding',
    'tconstruct:limb':'Bow Limb','tconstruct:bowstring':'Bowstring','tconstruct:grip':'Grip',
    'tconstruct:plating_helmet':'Helmet Plating','tconstruct:plating_chestplate':'Chestplate Plating',
    'tconstruct:plating_leggings':'Leggings Plating','tconstruct:plating_boots':'Boots Plating',
    'tconstruct:maille':'Maille','tconstruct:cuirass':'Cuirass',
  };
  return map[st] || toTitleCase(st.replace(/^.*:/, '').replace(/_/g, ' '));
}

// ═══════════════════════════════════════════════════════════════
// ═══════════════════════════════════════════════════════════════
// DATA ACCESS  (reads from the bundled window.TC3_DATA)
// ═══════════════════════════════════════════════════════════════

// Directory listing: mirrors the old GitHub API response — a list of
// file names (without .json) in the given datapack directory.
async function apiListDir(path) {
  return (DATA.dirs[path] ?? []).slice();
}

// File lookup: mirrors the old raw-file fetch — parsed JSON, or null
// when the bundle has no such path (same semantics as a 404 before).
async function fetchRaw(path) {
  return DATA.files[path] ?? null;
}

// ═══════════════════════════════════════════════════════════════
// PARSERS
// ═══════════════════════════════════════════════════════════════
function inferTier(headRaw) {
  if (!headRaw) return 2;
  const map = {'minecraft:wood':1,'minecraft:stone':1,'minecraft:gold':1,'minecraft:iron':2,'minecraft:diamond':3,'minecraft:netherite':4};
  return map[headRaw.mining_tier] ?? 2;
}

function lookupTrait(traitId, level, lang) {
  const key = traitId.replace(/^.*:/, '');
  const nameRaw = lang?.[`modifier.tconstruct.${key}`] || toTitleCase(key.replace(/_/g, ' '));
  const desc    = lang?.[`modifier.tconstruct.${key}.description`] || '';
  const name    = nameRaw + (level ? ' ' + toRoman(level) : '');
  return { name, desc };
}

function parseMaterial(name, statsJson, traitsJson, defJson, lang) {
  if (!statsJson?.stats) return null;
  const s = statsJson.stats;

  const headRaw   = s['tconstruct:head'];
  const handleRaw = s['tconstruct:handle'];
  const gripRaw   = s['tconstruct:grip'];
  const limbRaw   = s['tconstruct:limb'];
  const hasMaille  = 'tconstruct:maille'  in s;
  const hasCuirass = 'tconstruct:cuirass' in s;

  // Per-piece armor plating stats (armor, dur, toughness, knockback_resistance)
  const platings = {};
  for (const pt of ['plating_helmet','plating_chestplate','plating_leggings','plating_boots','plating_shield']) {
    const raw = s[`tconstruct:${pt}`];
    if (raw) platings[pt] = {
      armor: raw.armor ?? 0,
      dur:   raw.durability ?? 0,
      tough: raw.toughness  ?? 0,
      kbRes: raw.knockback_resistance ?? 0,
    };
  }
  const hasPlating = Object.keys(platings).length > 0;

  // Skip materials with no melee/mining/armor-relevant stats
  if (!headRaw && !handleRaw && !s['tconstruct:binding'] && !hasPlating && !hasMaille && !hasCuirass) return null;

  const tier      = defJson?.tier ?? inferTier(headRaw);

  const head = headRaw ? {
    dur:  headRaw.durability    ?? 0,
    atk:  headRaw.melee_attack  ?? 0,
    mspd: headRaw.mining_speed  ?? 0,
    tier: headRaw.mining_tier   ?? 'minecraft:wood',
  } : null;

  const handle = handleRaw ? {
    durMult:  handleRaw.durability    ?? 0,
    dmg:      handleRaw.melee_damage  ?? 0,
    spd:      handleRaw.melee_speed   ?? 0,
    mspdMult: handleRaw.mining_speed  ?? 0,
  } : null;

  // Grip stat (used by bow_grip and swasher-style tools):
  // durability = multiplier, melee_damage = flat bonus (accuracy is ranged-only, ignored here)
  // spd/mspdMult default to 0 so WIZ_HANDLE_WEIGHTS can be reused without NaN
  const grip = gripRaw ? {
    durMult:  gripRaw.durability   ?? 0,
    dmg:      gripRaw.melee_damage ?? 0,
    spd:      0,
    mspdMult: 0,
  } : null;

  const limbDur = limbRaw?.durability ?? undefined;
  const binding = 'tconstruct:binding' in s;

  // Parse default traits
  const traits = (traitsJson?.default ?? []).map(t => {
    const { name, desc } = lookupTrait(t.name, t.level, lang);
    return { id: t.name.replace(/^.*:/, ''), level: t.level ?? 1, name, desc, src: 'default' };
  });

  // Parse perStat traits (context-dependent: only apply when the tool matches the stat type).
  // Key: stat type short-name (e.g. 'melee_harvest', 'armor', 'ranged').
  const perStatTraits = {};
  for (const [statType, traitArr] of Object.entries(traitsJson?.perStat ?? {})) {
    const key = statType.replace(/^.*:/, '');
    perStatTraits[key] = traitArr.map(t => {
      const { name, desc } = lookupTrait(t.name, t.level, lang);
      return { id: t.name.replace(/^.*:/, ''), level: t.level ?? 1, name, desc, src: 'perStat' };
    });
  }

  // Try lang for display name: 'material.tconstruct.iron' → 'Iron'
  const langKey = `material.tconstruct.${name}`;
  const display = (lang?.[langKey]) || toTitleCase(name.replace(/_/g, ' '));

  return { display, tier, head, handle, grip, limbDur, binding, hasMaille, hasCuirass, platings, traits, perStatTraits };
}

function parseTool(name, toolJson, lang) {
  if (!toolJson?.modules) return null;
  const M = toolJson.modules;

  const partStatsMod  = M.find(m => m.type === 'tconstruct:part_stats');
  const matStatsMod   = M.find(m => m.type === 'tconstruct:material_stats');
  const baseStatsMod  = M.find(m => m.type === 'tconstruct:base_stats');
  const multiplyMod   = M.find(m => m.type === 'tconstruct:multiply_stats');
  const slotsMod      = M.find(m => m.type === 'tconstruct:modifier_slots');
  const traitsMod     = M.find(m => m.type === 'tconstruct:traits');

  let parts = [];

  if (partStatsMod?.parts) {
    // Count duplicates for labelling
    const itemCounts = {}, itemSeen = {};
    for (const p of partStatsMod.parts) {
      const item = typeof p === 'string' ? p : (p.item ?? '');
      itemCounts[item] = (itemCounts[item] || 0) + 1;
    }
    for (const p of partStatsMod.parts) {
      const item     = typeof p === 'string' ? p : (p.item ?? '');
      const scale    = typeof p === 'string' ? 1.0 : (p.scale ?? 1.0);
      const statType = ITEM_STAT[item];
      if (!statType) continue; // unmapped item (armor plating, etc.) — skip

      itemSeen[item] = (itemSeen[item] || 0) + 1;
      let label = itemLabel(item);
      if (itemCounts[item] > 1) label += ` ${toRoman(itemSeen[item])}`;
      if (scale < 1)            label += ` (×${scale})`;
      parts.push({ label, statType, scale });
    }
  } else if (matStatsMod?.stat_types) {
    const typeCounts = {}, typeSeen = {};
    for (const stEntry of matStatsMod.stat_types) {
      const st = typeof stEntry === 'string' ? stEntry : (stEntry.stat ?? '');
      typeCounts[st] = (typeCounts[st] || 0) + 1;
    }
    for (const stEntry of matStatsMod.stat_types) {
      const st    = typeof stEntry === 'string' ? stEntry : (stEntry.stat ?? '');
      const scale = typeof stEntry === 'object'  ? (stEntry.scale ?? 1.0) : 1.0;
      const localType = TC_STAT_TYPE[st] ?? 'unknown';
      if (localType === 'unknown' || localType === 'skull') continue;
      typeSeen[st] = (typeSeen[st] || 0) + 1;
      let label = statTypeLabel(st);
      if (typeCounts[st] > 1) label += typeSeen[st] === 1 ? ' (Primary)' : ' (Secondary)';
      parts.push({ label, statType: localType, scale });
    }
  }

  // Fixed-stat tools (like staves) have no material parts but are still valid
  const isFixedStat = parts.length === 0 && !!baseStatsMod;
  // Only include tools with stat-contributing parts, or known fixed-stat tools
  if (!isFixedStat && !parts.some(p => p.statType === 'head' || p.statType === 'handle' || ARMOR_PLATING_TYPES.has(p.statType))) return null;

  const bs   = baseStatsMod?.stats ?? {};
  const muls = multiplyMod?.multipliers ?? {};
  const slots = slotsMod?.slots ?? { upgrades: 3, abilities: 1 };

  const builtIn = (traitsMod?.traits ?? []).map(t => {
    const { name, desc } = lookupTrait(t.name, t.level, lang);
    return desc ? `${name} — ${desc}` : name;
  });

  const meta    = TOOL_META[name] ?? { icon: '🔧', group: 'Other', notes: '' };
  const display = meta.display || toTitleCase(name.replace(/_/g, ' '));

  const maxTierMod = M.find(m => m.type === 'tconstruct:max_tier');
  const tierCap    = maxTierMod?.tier ?? null; // e.g. 'minecraft:gold'

  // Read fixed default materials (e.g. travelers armor specifies rose_gold + leather)
  const defaultMatMod = M.find(m => m.type === 'tconstruct:default_materials');
  const defaultMaterials = (defaultMatMod?.materials ?? []).map(entry => {
    if (typeof entry === 'string') return entry.replace(/^.*:/, '');
    if (entry?.type === 'tconstruct:fixed') return (entry.material ?? '').replace(/^.*:/, '');
    return null;
  });

  return {
    display, icon: meta.icon, group: meta.group,
    parts,
    fixedStats: isFixedStat ? bs : null,
    baseAtk:    bs['tconstruct:attack_damage'] ?? 0,
    baseAtkSpd: bs['tconstruct:attack_speed']  ?? 1.0,
    multiply: {
      atk:  muls['tconstruct:attack_damage'] ?? 1,
      dur:  muls['tconstruct:durability']    ?? 1,
      mspd: muls['tconstruct:mining_speed']  ?? 1,
    },
    tierCap, slots, builtIn, notes: meta.notes, defaultMaterials,
  };
}

// ═══════════════════════════════════════════════════════════════
// LOADING UI
// ═══════════════════════════════════════════════════════════════
function setProgress(pct, status, detail) {
  document.getElementById('loadingBar').style.width = `${Math.min(100, pct)}%`;
  if (status) document.getElementById('loadingStatus').textContent = status;
  if (detail !== undefined) document.getElementById('loadingDetail').textContent = detail;
}

function showError(msg) {
  document.getElementById('loadingOverlay').style.display = 'flex';
  setProgress(100, 'Failed to load');
  const el = document.getElementById('loadingError');
  el.style.display = 'block';
  el.textContent   = msg;
  document.getElementById('retryBtn').style.display = 'inline-block';
}

// ═══════════════════════════════════════════════════════════════
// INITIALISATION — loads the bundled CABIN datapack (tc3_data.js)
// ═══════════════════════════════════════════════════════════════
async function init() {
  try {
    if (!DATA) return; // showError already queued by the header guard
    // ── Step 1: Directory listings from the bundle ─────────────
    setProgress(2, 'Loading bundled CABIN data…', '');
    const [statsFiles, traitsFiles, toolFiles, defFiles, upgradeRecFiles, abilityRecFiles, defenseRecFiles, modDefFiles] = await Promise.all([
      apiListDir(TC + 'materials/stats'),
      apiListDir(TC + 'materials/traits'),
      apiListDir(TC + 'tool_definitions'),
      apiListDir(TC + 'materials/definition'),
      apiListDir(MOD_RECIPE_BASE + 'upgrade').catch(() => []),
      apiListDir(MOD_RECIPE_BASE + 'ability').catch(() => []),
      apiListDir(MOD_RECIPE_BASE + 'defense').catch(() => []),
      apiListDir(TC + 'modifiers').catch(() => []),
    ]);
    const modDefSet = new Set(modDefFiles); // fast lookup: does tinkering/modifiers/{name}.json exist?

    const total = statsFiles.length + traitsFiles.length + toolFiles.length + defFiles.length + 1
                + upgradeRecFiles.length + abilityRecFiles.length + defenseRecFiles.length;
    let done = 0;
    const tick = () => {
      done++;
      setProgress(5 + (done / total) * 88, undefined,
        `Loaded ${done} / ${total} bundled files`);
    };

    // ── Step 2: Read all files from the bundle ─────────────────
    setProgress(5, `Reading ${total} bundled files…`, '');

    const raw    = (subpath) => fetchRaw(TC + subpath).then(d => { tick(); return d; });
    const recRaw = (slot, n) => fetchRaw(MOD_RECIPE_BASE + slot + '/' + n + '.json').then(d => { tick(); return [d, slot]; });

    const [statsArr, traitsArr, toolArr, defArr, lang, upgradeRecArr, abilityRecArr, defenseRecArr] = await Promise.all([
      Promise.all(statsFiles.map(n => raw(`materials/stats/${n}.json`).then(d => [n, d]))),
      Promise.all(traitsFiles.map(n => raw(`materials/traits/${n}.json`).then(d => [n, d]))),
      Promise.all(toolFiles.map(n => raw(`tool_definitions/${n}.json`).then(d => [n, d]))),
      Promise.all(defFiles.map(n => raw(`materials/definition/${n}.json`).then(d => [n, d]))),
      fetchRaw(LANG_PATH).then(d => { tick(); return d ?? {}; }),
      Promise.all(upgradeRecFiles.map(n => recRaw('upgrade', n))),
      Promise.all(abilityRecFiles.map(n => recRaw('ability', n))),
      Promise.all(defenseRecFiles.map(n => recRaw('defense', n))),
    ]);

    // ── Step 3: Build lookup maps ──────────────────────────────
    setProgress(95, 'Parsing data…', '');

    const statsMap  = Object.fromEntries(statsArr.filter(([,d]) => d).map(([n,d]) => [n,d]));
    const traitsMap = Object.fromEntries(traitsArr.filter(([,d]) => d).map(([n,d]) => [n,d]));
    const defMap    = Object.fromEntries(defArr.filter(([,d]) => d).map(([n,d]) => [n,d]));

    // ── Step 4: Parse materials ────────────────────────────────
    // CABIN availability (from the bundle) is authoritative:
    //  - unavailable: material has no source in the pack — hidden entirely
    //  - available:   pack provides it — shown by default, regardless of
    //                 Mods-panel state, unless the user has saved prefs
    const CABIN_AVAIL   = new Set(DATA.cabin?.available ?? []);
    const CABIN_BLOCKED = new Set(DATA.cabin?.unavailable ?? []);
    for (const name of statsFiles) {
      const mat = parseMaterial(name, statsMap[name], traitsMap[name], defMap[name], lang);
      if (!mat) continue;
      if (CABIN_BLOCKED.has(name)) continue;
      if (defMap[name]?.condition || MAT_TO_MOD[name]) {
        // Conditional/hidden/integration material — stored separately so the
        // Mods panel can still toggle it for what-if scenarios.
        CONDITIONAL_MATERIALS[name] = mat;
        if ((CABIN_AVAIL.has(name) && !HAS_SAVED_INTEGRATIONS) ||
            ENABLED_INTEGRATIONS.has(MAT_TO_MOD[name])) MATERIALS[name] = mat;
      } else {
        MATERIALS[name] = mat;
      }
    }

    // ── Step 5: Parse tools, filter, sort ─────────────────────
    const parsed = toolArr
      .map(([n, d]) => [n, parseTool(n, d, lang)])
      .filter(([, t]) => !!t);

    parsed.sort(([a], [b]) => {
      const ai = TOOL_ORDER.indexOf(a), bi = TOOL_ORDER.indexOf(b);
      if (ai === -1 && bi === -1) return a.localeCompare(b);
      if (ai === -1) return 1;
      if (bi === -1) return -1;
      return ai - bi;
    });
    for (const [n, t] of parsed) TOOLS[n] = t;

    // ── Step 6: Build modifier definitions from recipe data ───
    setProgress(96, 'Loading modifier definitions…', '');

    // Deduplicate recipe results by modifier name; track slot type and max level.
    // Slot type comes from recipe.slots if present, otherwise from the folder name.
    const modSlotMap = {}; // name → { slot, maxLevel }
    for (const [recipe, folderSlot] of [...upgradeRecArr, ...abilityRecArr, ...defenseRecArr]) {
      if (!recipe?.result) continue;
      // result is usually a plain string; some recipes (e.g. crystalshot variants) use {name, value}
      const resultId = typeof recipe.result === 'string' ? recipe.result : recipe.result?.name;
      if (!resultId) continue;
      const name   = resultId.replace(/^.*:/, '');
      const maxLvl = recipe.level?.max ?? (typeof recipe.level === 'number' ? recipe.level : 1);
      let slot = null;
      if (recipe.slots) {
        slot = recipe.slots.upgrades ? 'upgrades' : recipe.slots.abilities ? 'abilities' : recipe.slots.defense ? 'defense' : null;
      } else {
        slot = folderSlot; // infer from subfolder when recipe omits slots (e.g. luck_level_2)
      }
      if (!slot) continue;
      if (!modSlotMap[name]) {
        modSlotMap[name] = { slot, maxLevel: maxLvl };
      } else if (maxLvl > modSlotMap[name].maxLevel) {
        modSlotMap[name].maxLevel = maxLvl;
      }
    }

    // Fetch modifier definition JSONs — only for names that actually have a file (avoids 404s)
    const modNames  = Object.keys(modSlotMap);
    const modDefArr = await Promise.all(
      modNames
        .filter(n => modDefSet.has(n))
        .map(n => fetchRaw(TC + 'modifiers/' + n + '.json').then(d => [n, d]))
    );
    setProgress(99, 'Building modifier panel…', `${modNames.length} modifiers found`);

    // stat ID → internal key used by applyModifierBonuses
    const MOD_STAT = {
      'tconstruct:attack_damage': 'atk',
      'tconstruct:mining_speed':  'mspd',
      'tconstruct:attack_speed':  'atkSpd',
      'tconstruct:durability':    'dur',
    };
    // Build a lookup from fetched def files; modifiers without a def file get null modJson
    const modJsonMap = Object.fromEntries(modDefArr);

    // \u2500\u2500 Fetch trait modifier JSONs \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
    // Material traits reference modifier IDs (e.g. tconstruct:lightweight).
    // Collect all unique trait IDs from the raw traits data, then fetch
    // their modifier JSONs to extract numeric stat effects.
    const traitIds = new Set();
    for (const [, tj] of traitsArr) {
      for (const t of (tj?.default ?? [])) {
        traitIds.add(t.name.replace(/^.*:/, ''));
      }
    }
    const traitDefArr = await Promise.all(
      [...traitIds]
        .filter(n => modDefSet.has(n) && !modJsonMap[n])
        .map(n => fetchRaw(TC + 'modifiers/' + n + '.json').then(d => [n, d]))
    );
    TRAIT_EFFECTS = {};
    for (const [name, modJson] of traitDefArr) {
      if (!modJson) continue;
      const effects = [];
      for (const m of (modJson.modules ?? [])) {
        if (m.type !== 'tconstruct:stat_boost') continue;
        const stat = MOD_STAT[m.stat];
        if (!stat) continue;
        const eff = { stat, op: m.operation };
        if (m.flat            != null) eff.flat     = m.flat;
        if (m.each_level      != null) eff.eachLevel = m.each_level;
        if (m.modifier_level?.min != null) eff.minLevel = m.modifier_level.min;
        if (m.modifier_level?.max != null) eff.maxLevel = m.modifier_level.max;
        effects.push(eff);
      }
      if (effects.length) TRAIT_EFFECTS[name] = effects;
    }

    MODIFIER_DEFS = {};
    for (const name of modNames) {
      const info    = modSlotMap[name];
      if (!info) continue;
      const modJson = modJsonMap[name] ?? null;
      const display = lang['modifier.tconstruct.' + name]                  || toTitleCase(name.replace(/_/g, ' '));
      const desc    = lang['modifier.tconstruct.' + name + '.description'] || '';
      const effects = [];
      for (const m of (modJson?.modules ?? [])) {
        if (m.type === 'tconstruct:stat_boost') {
          const stat = MOD_STAT[m.stat];
          if (!stat) continue;
          const eff = { stat, op: m.operation };
          if (m.flat            != null) eff.flat     = m.flat;
          if (m.each_level      != null) eff.eachLevel = m.each_level;
          if (m.modifier_level?.min != null) eff.minLevel = m.modifier_level.min;
          if (m.modifier_level?.max != null) eff.maxLevel = m.modifier_level.max;
          effects.push(eff);
        } else if (m.type === 'tconstruct:set_stat' && m.stat === 'tconstruct:harvest_tier') {
          effects.push({ stat: 'tier', op: 'set_min', value: m.value });
        }
      }
      MODIFIER_DEFS[name] = { display, slot: info.slot, maxLevel: info.maxLevel, desc, effects };
    }

    setProgress(100, `Loaded ${Object.keys(MATERIALS).length} materials · ${Object.keys(TOOLS).length} tools · ${Object.keys(MODIFIER_DEFS).length} modifiers`, '');
    await new Promise(r => setTimeout(r, 350)); // brief pause to show 100%

    // ── Step 7: Init UI ───────────────────────────────────────
    document.getElementById('loadingOverlay').style.display = 'none';
    // Restore last session; fall back to first tool with defaults
    if (!autoLoad()) {
      currentTool  = Object.keys(TOOLS)[0];
      currentGroup = TOOLS[currentTool]?.group ?? '';
      const firstTool = TOOLS[currentTool];
      firstTool.parts.forEach((part, i) => {
        selectedMaterials[i] = pickDefaultMat(firstTool, i, part.statType);
      });
    }
    renderAll();
    renderBuilds();

  } catch (err) {
    console.error(err);
    showError(err.message || String(err));
  }
}

// ═══════════════════════════════════════════════════════════════
// CALCULATION
// ═══════════════════════════════════════════════════════════════

// Compute aggregate bonuses from a { modKey: level } map
function applyModifierBonuses(mods) {
  let addDur = 0, addAtk = 0, addMspd = 0;
  let mulDur = 1, mulAtk = 1, mulMspd = 1, mulAtkSpd = 1;
  const tierBoosts = [];
  for (const [key, level] of Object.entries(mods)) {
    if (!level) continue;
    const def = MODIFIER_DEFS[key];
    if (!def) continue;
    for (const eff of def.effects) {
      if (eff.minLevel != null && level < eff.minLevel) continue;
      if (eff.maxLevel != null && level > eff.maxLevel) continue;
      const val = (eff.flat ?? 0) + (eff.eachLevel ?? 0) * level;
      switch (eff.op) {
        case 'add':
          if (eff.stat === 'dur')  addDur  += val;
          if (eff.stat === 'atk')  addAtk  += val;
          if (eff.stat === 'mspd') addMspd += val;
          break;
        case 'multiply_base':
        case 'multiply_conditional':
          if (eff.stat === 'dur')    mulDur    *= (1 + val);
          if (eff.stat === 'atk')    mulAtk    *= (1 + val);
          if (eff.stat === 'mspd')   mulMspd   *= (1 + val);
          if (eff.stat === 'atkSpd') mulAtkSpd *= (1 + val);
          break;
        case 'set_min':
          tierBoosts.push(eff.value);
          break;
      }
    }
  }
  return { addDur, addAtk, addMspd, mulDur, mulAtk, mulMspd, mulAtkSpd, tierBoosts };
}

function calcStats(toolKey, matKeys, mods = {}) {
  const tool  = TOOLS[toolKey];

  // Fixed-stat tools (staves) have no material parts
  if (tool.fixedStats) {
    const bs = tool.fixedStats;
    const b  = applyModifierBonuses(mods);
    const baseDur = bs['tconstruct:durability'] ?? 0;
    return {
      dur:        Math.round(baseDur * b.mulDur),
      atk: 0, atkSpd: 0, mspd: 0, dps: 0,
      tier: 'minecraft:wood',
      traits: [],
      // Staff-specific stats
      blockAmt:   bs['tconstruct:block_amount']     ?? 0,
      blockAngle: bs['tconstruct:block_angle']      ?? 90,
      projDmg:    bs['tconstruct:projectile_damage'] ?? 0,
      accuracy:   bs['tconstruct:accuracy']          ?? 0,
      drawSpeed:  bs['tconstruct:draw_speed']        ?? 0,
      velocity:   bs['tconstruct:velocity']          ?? 0,
      useSpd:     bs['tconstruct:use_item_speed']    ?? 0,
    };
  }

  const parts = tool.parts;
  let headDur = 0, handleDurMult = 0, atk = 0, handleDmg = 0, handleSpd = 0,
      headMspd = 0, handleMspdMult = 0;
  let armorVal = 0, armorTough = 0, armorKbRes = 0; // armor piece stats
  let bestTier = 'minecraft:wood';
  const traits = [], seen = new Set();
  let traitAtkAdd = 0, traitMspdAdd = 0, traitAtkSpdAdd = 0, traitDurMul = 1, traitAtkMul = 1;

  // melee_harvest perStat traits apply when the tool can both fight and mine (has a head part)
  const isMeleeHarvest = parts.some(p => p.statType === 'head');

  // Pre-count how many parts use each material key (for trait level stacking)
  const matPartCount = {};
  for (let i = 0; i < parts.length; i++) {
    const k = matKeys[i];
    if (MATERIALS[k]) matPartCount[k] = (matPartCount[k] || 0) + 1;
  }

  for (let i = 0; i < parts.length; i++) {
    const { statType, scale } = parts[i];
    const mat = MATERIALS[matKeys[i]];
    if (!mat) continue;

    if (statType === 'head' && mat.head) {
      headDur  += mat.head.dur  * scale;
      atk      += mat.head.atk  * scale;
      headMspd += mat.head.mspd * scale;
      const t = mat.head.tier;
      if ((TIERS[t.split(':')[1]] ?? 0) > (TIERS[bestTier.split(':')[1]] ?? 0)) bestTier = t;
    } else if (statType === 'handle' && mat.handle) {
      handleDurMult  += mat.handle.durMult  * scale;
      handleDmg      += mat.handle.dmg       * scale;
      handleSpd      += mat.handle.spd       * scale;
      handleMspdMult += mat.handle.mspdMult  * scale;
    } else if (statType === 'grip' && (mat.grip || mat.handle)) {
      const g = mat.grip ?? mat.handle;
      handleDurMult += g.durMult * scale;
      handleDmg     += g.dmg     * scale;
    } else if (statType === 'limb' && mat.limbDur) {
      headDur += mat.limbDur * scale; // limb contributes flat durability only
    } else if (ARMOR_PLATING_TYPES.has(statType) && mat.platings?.[statType]) {
      const p = mat.platings[statType];
      headDur    += p.dur   * scale;
      armorVal   += p.armor * scale;
      armorTough += p.tough * scale;
      armorKbRes += p.kbRes * scale;
    }
    // binding / bowstring / grip / maille / cuirass: traits only

    // Apply default traits — effects fire once per unique (trait, material) pair,
    // but at the accumulated level (base_level × number of parts using this material).
    for (const tr of (mat.traits ?? [])) {
      const k = tr.name + matKeys[i];
      if (seen.has(k)) continue;
      seen.add(k);
      traits.push({ ...tr, level: (tr.level ?? 1) * (matPartCount[matKeys[i]] || 1), material: mat.display });
      const effs = TRAIT_EFFECTS[tr.id];
      if (effs) {
        const lvl = (tr.level ?? 1) * (matPartCount[matKeys[i]] || 1);
        for (const e of effs) {
          if (e.minLevel != null && lvl < e.minLevel) continue;
          if (e.maxLevel != null && lvl > e.maxLevel) continue;
          const val = (e.flat ?? 0) + (e.eachLevel ?? 0) * lvl;
          if (e.op === 'add') {
            if (e.stat === 'atk')    traitAtkAdd    += val;
            if (e.stat === 'mspd')   traitMspdAdd   += val;
            if (e.stat === 'atkSpd') traitAtkSpdAdd += val;
          } else if (e.op === 'multiply_base' || e.op === 'multiply_conditional') {
            if (e.stat === 'dur') traitDurMul *= (1 + val);
            if (e.stat === 'atk') traitAtkMul *= (1 + val);
          }
        }
      }
    }

    // Apply melee_harvest perStat traits (e.g. Fortune from ancient hide)
    // These activate on any tool that can both attack and mine (has a head part).
    if (isMeleeHarvest && mat.perStatTraits?.melee_harvest) {
      for (const tr of mat.perStatTraits.melee_harvest) {
        const k = `ps:${tr.name}:${matKeys[i]}`;
        if (!seen.has(k)) { seen.add(k); traits.push({ ...tr, material: mat.display }); }
      }
    }
  }

  const b = applyModifierBonuses(mods);

  // Tier: take max of material tier and any modifier tier boosts
  for (const t of b.tierBoosts) {
    if ((TIERS[t.split(':')[1]] ?? 0) > (TIERS[bestTier.split(':')[1]] ?? 0)) bestTier = t;
  }
  // Apply tool-level tier cap (e.g. pickadze is capped at Gold)
  if (tool.tierCap && (TIERS[bestTier.split(':')[1]] ?? 0) > (TIERS[tool.tierCap.split(':')[1]] ?? 0)) {
    bestTier = tool.tierCap;
  }

  // Java FloatToolStat formula: (base + add) * (1 + percent) * multiply
  // Modifier ADD effects go into the `add` bucket (compound with head material stats)
  // Modifier MULTIPLY_BASE/CONDITIONAL effects multiply the `multiply` factor
  const dur    = Math.round((headDur + b.addDur) * (1 + handleDurMult) * tool.multiply.dur * b.mulDur * traitDurMul);
  const atkFin = +((tool.baseAtk + atk + b.addAtk + traitAtkAdd) * (1 + handleDmg) * tool.multiply.atk * b.mulAtk * traitAtkMul).toFixed(2);
  const atkSpd = +((tool.baseAtkSpd + traitAtkSpdAdd) * (1 + handleSpd) * b.mulAtkSpd).toFixed(2);
  const mspd   = +((headMspd + b.addMspd + traitMspdAdd) * (1 + handleMspdMult) * tool.multiply.mspd * b.mulMspd).toFixed(2);
  const dps    = +(atkFin * atkSpd).toFixed(2);

  return { dur, atk: atkFin, atkSpd, mspd, dps, tier: bestTier, traits,
           armor: +armorVal.toFixed(1), toughness: +armorTough.toFixed(1), kbRes: +armorKbRes.toFixed(2) };
}

/**
 * Compute the theoretical per-stat maximums for a tool based on available materials.
 * Uses a greedy approach: independently picks the best material value for each slot,
 * which gives a tight upper bound for bar scaling in the stats panel.
 */
function calcToolMaxStats(toolKey) {
  const tool = TOOLS[toolKey];
  if (!tool) return { dur: 1, atk: 1, mspd: 1, atkSpd: 0.1, dps: 1, armor: 1, toughness: 1, kbRes: 0.01 };
  if (tool.fixedStats) return { dur: tool.fixedStats['tconstruct:durability'] ?? 1, atk: 1, mspd: 1, atkSpd: 0.1, dps: 1, armor: 1, toughness: 1, kbRes: 0.01 };

  const allMats = Object.values(MATERIALS);

  // Per-slot-type best values
  let bHeadDur = 0, bHeadAtk = 0, bHeadMspd = 0;
  let bHandleDurMult = 0, bHandleDmg = -Infinity, bHandleSpd = -Infinity, bHandleMspdMult = 0;
  let bGripDurMult = 0, bGripDmg = -Infinity;
  let bLimbDur = 0;
  for (const m of allMats) {
    if (m.head)   { bHeadDur  = Math.max(bHeadDur,  m.head.dur);  bHeadAtk  = Math.max(bHeadAtk,  m.head.atk);  bHeadMspd = Math.max(bHeadMspd, m.head.mspd); }
    if (m.handle) { bHandleDurMult = Math.max(bHandleDurMult, m.handle.durMult); bHandleDmg = Math.max(bHandleDmg, m.handle.dmg); bHandleSpd = Math.max(bHandleSpd, m.handle.spd); bHandleMspdMult = Math.max(bHandleMspdMult, m.handle.mspdMult); }
    if (m.grip || m.handle) { const g = m.grip ?? m.handle; bGripDurMult = Math.max(bGripDurMult, g.durMult); bGripDmg = Math.max(bGripDmg, g.dmg); }
    if (m.limbDur) bLimbDur = Math.max(bLimbDur, m.limbDur);
  }
  if (!isFinite(bHandleDmg))  bHandleDmg  = 0;
  if (!isFinite(bHandleSpd))  bHandleSpd  = 0;
  if (!isFinite(bGripDmg))    bGripDmg    = 0;

  let totHeadDur = 0, totHeadAtk = 0, totHeadMspd = 0;
  let totHandleDurMult = 0, totHandleDmg = 0, totHandleSpd = 0, totHandleMspdMult = 0;
  let armor = 0, toughness = 0, kbRes = 0;

  for (const { statType, scale } of tool.parts) {
    if      (statType === 'head')   { totHeadDur += bHeadDur * scale; totHeadAtk += bHeadAtk * scale; totHeadMspd += bHeadMspd * scale; }
    else if (statType === 'limb')   { totHeadDur += bLimbDur * scale; }
    else if (statType === 'handle') { totHandleDurMult += bHandleDurMult * scale; totHandleDmg += bHandleDmg * scale; totHandleSpd += bHandleSpd * scale; totHandleMspdMult += bHandleMspdMult * scale; }
    else if (statType === 'grip')   { totHandleDurMult += bGripDurMult * scale; totHandleDmg += bGripDmg * scale; }
    else if (ARMOR_PLATING_TYPES.has(statType)) {
      let bA = 0, bT = 0, bK = 0;
      for (const m of allMats) { const p = m.platings?.[statType]; if (p) { bA = Math.max(bA, p.armor); bT = Math.max(bT, p.tough); bK = Math.max(bK, p.kbRes); } }
      armor += bA * scale; toughness += bT * scale; kbRes += bK * scale;
    }
  }

  const dur    = Math.max(1, totHeadDur * (1 + totHandleDurMult) * tool.multiply.dur);
  const atk    = Math.max(1, (tool.baseAtk + totHeadAtk) * (1 + Math.max(0, totHandleDmg)) * tool.multiply.atk);
  const atkSpd = Math.max(0.1, tool.baseAtkSpd * (1 + Math.max(0, totHandleSpd)));
  const mspd   = Math.max(1, totHeadMspd * (1 + totHandleMspdMult) * tool.multiply.mspd);
  const dps    = Math.max(1, atk * atkSpd);

  return { dur, atk, mspd, atkSpd, dps, armor: Math.max(1, armor), toughness: Math.max(1, toughness), kbRes: Math.max(0.01, kbRes) };
}

function scoreStats(stats, goal) {
  // Mining tier: how capable the combo is at breaking blocks (0=wood … 4=netherite).
  // This is a functional stat (what ores you can mine), not a material quality gate.
  const tierVal = TIERS[stats.tier?.split(':')[1]] ?? 0;
  if (goal === 'defense')    return (stats.armor ?? 0) * 100 + (stats.toughness ?? 0) * 50 + (stats.kbRes ?? 0) * 20 + stats.dur * 0.03;
  if (goal === 'dps')        return stats.dps * 100;
  if (goal === 'damage')     return stats.atk * 100;
  if (goal === 'durability') return stats.dur;
  // Mining score weights harvest capability, speed, and tool longevity.
  // Durability matters for mining: a longer-lasting tool means less downtime repairing.
  if (goal === 'mining')     return stats.mspd * 40 + tierVal * 30 + stats.dur * 0.05;
  if (goal === 'custom') {
    const v = (id, fb) => +(document.getElementById(id)?.value ?? fb);
    return stats.dps    * v('wDps',    50)
         + stats.atk    * v('wAtk',     0)
         + stats.atkSpd * v('wAtkSpd',  0)
         + stats.dur    * v('wDur',  0.03)
         + stats.mspd   * v('wMspd',    5)
         + tierVal      * v('wTier',    0);
  }
  // Balanced: DPS and durability dominate; mspd is a minor tiebreaker.
  return stats.dps * 50 + stats.dur * 0.03 + stats.mspd * 5;
}

function toggleCustomWeights() {
  const goal = document.getElementById('optGoal')?.value;
  const panel = document.getElementById('customWeights');
  if (panel) panel.style.display = goal === 'custom' ? '' : 'none';
}

// ═══════════════════════════════════════════════════════════════
// UI HELPERS
// ═══════════════════════════════════════════════════════════════
function materialOptions(statType, maxTier = 4) {
  return Object.entries(MATERIALS).filter(([, m]) => {
    if (m.tier > maxTier) return false;
    if (statType === 'head')      return !!m.head;
    if (statType === 'handle')    return !!m.handle;
    if (statType === 'binding')   return !!m.binding;
    if (statType === 'limb')      return !!m.limbDur;
    if (statType === 'bowstring') return !!m.binding;        // use binding materials for bowstring slot
    if (statType === 'grip')      return !!(m.grip || m.handle); // prefer grip stat, fall back to handle
    if (ARMOR_PLATING_TYPES.has(statType)) return !!(m.platings?.[statType]);
    if (statType === 'maille')    return !!m.hasMaille;
    if (statType === 'cuirass')   return !!m.hasCuirass;
    return false;
  }).sort(([, a], [, b]) => b.tier - a.tier || a.display.localeCompare(b.display));
}

/** Pick the default material for a part slot.
 *  Prefers the tool's JSON-specified default (e.g. rose_gold for travelers armor),
 *  then the first non-hidden (non-tc3_hidden) material, then any material.
 */
function pickDefaultMat(tool, partIdx, statType) {
  const opts = materialOptions(statType);
  // 1. Use the tool's declared default if it's valid for this slot
  const declared = tool?.defaultMaterials?.[partIdx];
  if (declared && opts.some(([k]) => k === declared)) return declared;
  // 2. First craftable (non tc3_hidden) material
  const craftable = opts.find(([k]) => MAT_TO_MOD[k] !== 'tc3_hidden');
  if (craftable) return craftable[0];
  // 3. Anything available
  return opts[0]?.[0] ?? '';
}

// ═══════════════════════════════════════════════════════════════
// OPTIMIZER HELPERS — dominance pruning & Pareto filter
// ═══════════════════════════════════════════════════════════════

// Returns true if material a strictly dominates b for the given slot type
function slotDominates(statType, a, b) {
  if (statType === 'head') {
    if (!a.head || !b.head) return false;
    const at = TIERS[a.head.tier?.split(':')[1]] ?? 0;
    const bt = TIERS[b.head.tier?.split(':')[1]] ?? 0;
    return a.head.dur  >= b.head.dur  && a.head.atk  >= b.head.atk &&
           a.head.mspd >= b.head.mspd && at >= bt &&
           (a.head.dur > b.head.dur || a.head.atk > b.head.atk ||
            a.head.mspd > b.head.mspd || at > bt);
  }
  if (statType === 'handle') {
    if (!a.handle || !b.handle) return false;
    return a.handle.durMult  >= b.handle.durMult  && a.handle.dmg      >= b.handle.dmg &&
           a.handle.spd      >= b.handle.spd       && a.handle.mspdMult >= b.handle.mspdMult &&
           (a.handle.durMult > b.handle.durMult || a.handle.dmg > b.handle.dmg ||
            a.handle.spd > b.handle.spd || a.handle.mspdMult > b.handle.mspdMult);
  }
  if (statType === 'limb') {
    return (a.limbDur ?? 0) > (b.limbDur ?? 0);
  }
  return false; // binding/bowstring/grip: no stat ordering
}

// Removes materials from a slot's candidate list if another material beats them on every stat
function pruneSlot(statType, options) {
  if (!['head', 'handle', 'limb'].includes(statType)) return options;
  const dominated = new Set();
  for (let i = 0; i < options.length; i++) {
    if (dominated.has(i)) continue;
    for (let j = 0; j < options.length; j++) {
      if (i === j || dominated.has(j)) continue;
      if (slotDominates(statType, options[i][1], options[j][1])) dominated.add(j);
    }
  }
  return options.filter((_, i) => !dominated.has(i));
}

// Removes combinations whose stats are dominated on ALL axes by another combo
// Uses Uint8Array for speed; O(n²) but n is small after per-slot pruning
function paretoFilter(results) {
  const n = results.length;
  if (n <= 1) return results;
  const dominated = new Uint8Array(n);
  for (let i = 0; i < n; i++) {
    if (dominated[i]) continue;
    const a = results[i].stats;
    const at = TIERS[a.tier?.split(':')[1]] ?? 0;
    for (let j = i + 1; j < n; j++) {
      if (dominated[j]) continue;
      const b = results[j].stats;
      const bt = TIERS[b.tier?.split(':')[1]] ?? 0;
      const aGeB = a.dur >= b.dur && a.atk >= b.atk && a.atkSpd >= b.atkSpd && a.mspd >= b.mspd && at >= bt;
      const aGtB = a.dur >  b.dur || a.atk >  b.atk || a.atkSpd >  b.atkSpd || a.mspd >  b.mspd || at >  bt;
      if (aGeB && aGtB) { dominated[j] = 1; continue; }
      const bGeA = b.dur >= a.dur && b.atk >= a.atk && b.atkSpd >= a.atkSpd && b.mspd >= a.mspd && bt >= at;
      const bGtA = b.dur >  a.dur || b.atk >  a.atk || b.atkSpd >  a.atkSpd || b.mspd >  a.mspd || bt >  at;
      if (bGeA && bGtA) { dominated[i] = 1; break; }
    }
  }
  return results.filter((_, i) => !dominated[i]);
}

function barHTML(cls, pct) {
  return `<div class="bar-track"><div class="bar-fill ${cls}" style="width:${Math.min(100,pct)}%"></div></div>`;
}
function tierBadgeHTML(tier) {
  const icon = TIER_ICON[tier];
  const label = TIER_LABEL[tier] ?? tier;
  const img = icon ? `<img src="${icon}" alt="${label}" class="tier-icon">` : '';
  return `<span class="tier-badge ${TIER_CLASS[tier]??''}" style="margin-top:0">${img}${label} Tier</span>`;
}

// ═══════════════════════════════════════════════════════════════
// RENDER
// ═══════════════════════════════════════════════════════════════
function renderToolTabs() {
  // Collect ordered unique groups
  const groups = [];
  for (const t of Object.values(TOOLS)) {
    if (!groups.includes(t.group)) groups.push(t.group);
  }

  // Group category row
  let groupHtml = '';
  for (const g of groups) {
    groupHtml += `<button class="group-tab${g === currentGroup ? ' active' : ''}" onclick="selectGroup('${g}')">${g}</button>`;
  }
  document.getElementById('toolGroupTabs').innerHTML = groupHtml;

  // Tool row — only tools in the active group
  let toolHtml = '';
  for (const [key, t] of Object.entries(TOOLS)) {
    if (t.group !== currentGroup) continue;
    const tabIcon = t.iconUrl
      ? `<img src="${t.iconUrl}" alt="${t.display}" class="tool-tab-icon">`
      : t.icon;
    toolHtml += `<button class="tool-tab${key === currentTool ? ' active' : ''}" onclick="selectTool('${key}')">${tabIcon} ${t.display}</button>`;
  }
  document.getElementById('toolTabs').innerHTML = toolHtml;
}

function selectGroup(group) {
  currentGroup = group;
  // Auto-select first tool in this group
  for (const [key, t] of Object.entries(TOOLS)) {
    if (t.group === group) { selectTool(key); return; }
  }
}

/** Initialize selectedMaterials defaults for the current tool (no rendering). */
function renderPartSlots() {
  const tool = TOOLS[currentTool];
  tool.parts.forEach((part, i) => {
    if (!selectedMaterials[i]) {
      selectedMaterials[i] = pickDefaultMat(tool, i, part.statType);
    }
  });
}

function renderStats() {
  const tool    = TOOLS[currentTool];
  const matKeys = tool.parts.map((_, i) => selectedMaterials[i]);
  const s       = calcStats(currentTool, matKeys, selectedModifiers);
  const mx      = calcToolMaxStats(currentTool);
  const MAX_DUR = mx.dur, MAX_ATK = mx.atk, MAX_MSPD = mx.mspd, MAX_AKS = mx.atkSpd, MAX_DPS = mx.dps;
  const goal    = document.getElementById('optGoal')?.value ?? 'balanced';

  const cardDur = `
    <div class="stat-card${goal==='durability'?' stat-card--goal':''}">
      <div class="stat-label">Durability</div>
      <div class="stat-value" style="color:#3ecf70">${s.dur.toLocaleString()}</div>
      <div class="stat-sub">×${tool.multiply.dur} mult</div>
      ${barHTML('bar-durability', s.dur/MAX_DUR*100)}
    </div>`;
  const cardDps = `
    <div class="stat-card${goal==='dps'?' stat-card--goal':''}">
      <div class="stat-label">DPS</div>
      <div class="stat-value" style="color:#c855e0">${s.dps}</div>
      <div class="stat-sub">${s.atk} × ${s.atkSpd}/s</div>
      ${barHTML('bar-dps', s.dps/MAX_DPS*100)}
    </div>`;
  const cardAtk = `
    <div class="stat-card${goal==='damage'?' stat-card--goal':''}">
      <div class="stat-label">Attack</div>
      <div class="stat-value" style="color:#e85555">${s.atk}</div>
      <div class="stat-sub">base ${tool.baseAtk} ×${tool.multiply.atk}</div>
      ${barHTML('bar-attack', s.atk/MAX_ATK*100)}
    </div>`;
  const cardSpd = `
    <div class="stat-card">
      <div class="stat-label">Atk Speed</div>
      <div class="stat-value" style="color:#e8872a">${s.atkSpd}</div>
      <div class="stat-sub">base ${tool.baseAtkSpd}</div>
      ${barHTML('bar-speed', s.atkSpd/MAX_AKS*100)}
    </div>`;
  const cardMining = `
    <div class="stat-card full-width${goal==='mining'?' stat-card--goal':''}">
      <div class="stat-label">Mining Speed</div>
      <div class="stat-value" style="color:#52acf0">${s.mspd}</div>
      <div style="display:flex;align-items:center;gap:8px">
        ${tierBadgeHTML(s.tier)}
        <span class="stat-sub" style="margin-top:0">×${tool.multiply.mspd}</span>
      </div>
      ${barHTML('bar-mining', s.mspd/MAX_MSPD*100)}
    </div>`;

  // Staff tools: fixed stats, no material parts
  const isStaffTool = TOOL_META[currentTool]?.group === 'Staffs';
  // Armor tools: show armor stats instead of DPS/mining
  const isArmorTool = TOOL_META[currentTool]?.group === 'Armor';
  let cards;
  if (isStaffTool) {
    const cardStaffDur = `
      <div class="stat-card">
        <div class="stat-label">Durability</div>
        <div class="stat-value" style="color:#3ecf70">${s.dur.toLocaleString()}</div>
        <div class="stat-sub">fixed base</div>
        ${barHTML('bar-durability', 100)}
      </div>`;
    const cardBlock = `
      <div class="stat-card">
        <div class="stat-label">Block Amount</div>
        <div class="stat-value" style="color:#5bb3ff">${s.blockAmt}</div>
        <div class="stat-sub">${s.blockAngle > 90 ? s.blockAngle + '° arc' : 'standard arc'}</div>
        ${barHTML('bar-armor', s.blockAmt / 35 * 100)}
      </div>`;
    const hasProj = s.projDmg > 0;
    const hasDraw = s.drawSpeed > 0;
    const cardProj = hasProj ? `
      <div class="stat-card">
        <div class="stat-label">Projectile Dmg</div>
        <div class="stat-value" style="color:#e85555">${s.projDmg}</div>
        <div class="stat-sub">accuracy ${s.accuracy ? (s.accuracy * 100).toFixed(0) + '%' : '—'}</div>
        ${barHTML('bar-attack', s.projDmg / 3 * 100)}
      </div>` : '';
    const cardDraw = hasDraw ? `
      <div class="stat-card">
        <div class="stat-label">Draw Speed</div>
        <div class="stat-value" style="color:#e07a20">${s.drawSpeed}×</div>
        <div class="stat-sub">velocity ${s.velocity}×</div>
        ${barHTML('bar-speed', s.drawSpeed / 1.25 * 100)}
      </div>` : '';
    const cardMoveSpd = `
      <div class="stat-card">
        <div class="stat-label">Move Spd (using)</div>
        <div class="stat-value" style="color:#52acf0">+${Math.round((s.useSpd ?? 0) * 100)}%</div>
        <div class="stat-sub">while holding RMB</div>
        ${barHTML('bar-mining', 100)}
      </div>`;
    cards = cardStaffDur + cardBlock + (cardProj || cardDraw) + cardMoveSpd;
  } else if (isArmorTool) {
    const MAX_ARMOR = mx.armor, MAX_TOUGH = mx.toughness, MAX_KBRES = mx.kbRes;
    const cardArmor = `
      <div class="stat-card${goal==='defense'?' stat-card--goal':''}">
        <div class="stat-label">Armor</div>
        <div class="stat-value" style="color:#5bb3ff">${s.armor ?? 0}</div>
        <div class="stat-sub">protection points</div>
        ${barHTML('bar-armor', (s.armor ?? 0)/MAX_ARMOR*100)}
      </div>`;
    const cardTough = `
      <div class="stat-card${goal==='defense'?' stat-card--goal':''}">
        <div class="stat-label">Toughness</div>
        <div class="stat-value" style="color:#c855e0">${s.toughness ?? 0}</div>
        <div class="stat-sub">reduces big hit penalty</div>
        ${barHTML('bar-toughness', (s.toughness ?? 0)/MAX_TOUGH*100)}
      </div>`;
    const cardKbRes = `
      <div class="stat-card">
        <div class="stat-label">Knockback Res.</div>
        <div class="stat-value" style="color:#e07a20">${s.kbRes ?? 0}</div>
        <div class="stat-sub">reduces knockback</div>
        ${barHTML('bar-kbres', (s.kbRes ?? 0)/MAX_KBRES*100)}
      </div>`;
    const cardDurArmor = `
      <div class="stat-card${goal==='durability'?' stat-card--goal':''}">
        <div class="stat-label">Durability</div>
        <div class="stat-value" style="color:#4caf7d">${s.dur.toLocaleString()}</div>
        <div class="stat-sub">×dur mult: ${tool.multiply.dur}</div>
        ${barHTML('bar-durability', s.dur/MAX_DUR*100)}
      </div>`;
    cards = cardArmor + cardTough + cardKbRes + cardDurArmor;
  } else {
    // Reorder cards so the goal-relevant stat appears first
    if (goal === 'mining') {
      cards = cardMining + cardDur + cardDps + cardAtk + cardSpd;
    } else if (goal === 'dps') {
      cards = cardDps + cardAtk + cardSpd + cardDur + cardMining;
    } else if (goal === 'damage') {
      cards = cardAtk + cardDps + cardSpd + cardDur + cardMining;
    } else if (goal === 'durability') {
      cards = cardDur + cardDps + cardAtk + cardSpd + cardMining;
    } else {
      cards = cardDur + cardDps + cardAtk + cardSpd + cardMining;
    }
  }

  document.getElementById('statsGrid').innerHTML = cards;

  renderTraits(s.traits);
}

const ROMAN = ['', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'];

/** Return a short human-readable string of computed stat effects for a trait at the given level.
 *  e.g. traitValueStr('tconstruct:momentum', 2) → "+0.40 MSpd"
 */
// Strip the baked-in Roman numeral suffix from a trait name and re-append the stacked level.
// e.g. stackedTraitName('Momentum I', 2) → 'Momentum II'
function stackedTraitName(traitName, stackedLevel) {
  const words = traitName.split(' ');
  const last  = words[words.length - 1];
  const baseName = words.length > 1 && (/^[IVXLCDM]+$/.test(last) || /^\d+$/.test(last))
    ? words.slice(0, -1).join(' ')
    : traitName;
  return stackedLevel > 0 ? `${baseName} ${toRoman(stackedLevel)}` : baseName;
}

function traitValueStr(traitId, level) {
  const effs = TRAIT_EFFECTS[traitId];
  if (!effs || !effs.length) return TRAIT_KNOWN[traitId]?.label ?? '';
  const STAT_LBL = { dur: 'Dur', atk: 'Atk', mspd: 'MSpd', atkSpd: 'AtkSpd' };
  const parts = [];
  for (const e of effs) {
    if (e.minLevel != null && level < e.minLevel) continue;
    if (e.maxLevel != null && level > e.maxLevel) continue;
    const val = (e.flat ?? 0) + (e.eachLevel ?? 0) * level;
    const lbl = STAT_LBL[e.stat] ?? e.stat;
    if (e.op === 'add') {
      parts.push(`${val >= 0 ? '+' : ''}${+val.toFixed(2)} ${lbl}`);
    } else {
      const pct = +(val * 100).toFixed(1);
      parts.push(`${val >= 0 ? '+' : ''}${pct}% ${lbl}`);
    }
  }
  return parts.join(', ');
}

function renderTraits(traits) {
  const builtIn = TOOLS[currentTool].builtIn ?? [];
  const builtInHTML = builtIn.map(b => {
    const [name, ...rest] = b.split(' — ');
    return `<div class="trait-item">
      <span class="trait-name">${name}</span>
      ${rest.length ? `<span class="trait-desc">${rest.join(' — ')}</span>` : ''}
      <span class="trait-source">Built-in to this tool</span>
    </div>`;
  }).join('');

  const matHTML = traits.length
    ? traits.map(t => {
        const lvl    = t.level ?? 1;
        const displayName = stackedTraitName(t.name, lvl);
        const valStr = traitValueStr(t.id, lvl);
        return `<div class="trait-item">
          <span class="trait-name">${escHtml(displayName)}</span>
          ${valStr ? `<span class="trait-value">${escHtml(valStr)}</span>` : ''}
          ${t.desc ? `<span class="trait-desc">${escHtml(t.desc)}</span>` : ''}
          <span class="trait-source">From: ${escHtml(t.material)}</span>
        </div>`;
      }).join('')
    : '<div class="no-traits">No material traits active</div>';

  document.getElementById('traitList').innerHTML = builtInHTML + matHTML;
}

function renderToolInfo() {
  const tool    = TOOLS[currentTool];
  const slotStr = Object.entries(tool.slots).map(([k, v]) => `${v} ${k}`).join(', ');
  document.getElementById('toolInfo').innerHTML = `
    <div class="info-row"><span class="info-key">Modifier slots</span><span class="info-val">${slotStr}</span></div>
    <div class="info-row"><span class="info-key">Attack mult</span><span class="info-val">×${tool.multiply.atk}</span></div>
    <div class="info-row"><span class="info-key">Durability mult</span><span class="info-val">×${tool.multiply.dur}</span></div>
    <div class="info-row"><span class="info-key">Mining mult</span><span class="info-val">×${tool.multiply.mspd}</span></div>
    <div class="info-row" style="margin-top:4px"><span class="info-key" style="color:var(--accent2)">Notes</span><span class="info-val" style="font-weight:400;color:var(--muted)">${tool.notes}</span></div>`;
}

function renderModifiers() {
  const tool = TOOLS[currentTool];
  const availSlots = tool.slots ?? {};
  const upgrades = availSlots.upgrades ?? 0;
  const abilities = availSlots.abilities ?? 0;
  const defense   = availSlots.defense  ?? 0;

  let usedUpgrades = 0, usedAbilities = 0, usedDefense = 0;
  for (const [key, level] of Object.entries(selectedModifiers)) {
    if (!level) continue;
    const def = MODIFIER_DEFS[key];
    if (!def) continue;
    if (def.slot === 'upgrades') usedUpgrades += level;
    else if (def.slot === 'abilities') usedAbilities += level;
    else if (def.slot === 'defense')  usedDefense  += level;
  }

  const upgFull = upgrades > 0 && usedUpgrades >= upgrades;
  const abiFull = abilities > 0 && usedAbilities >= abilities;
  const defFull = defense  > 0 && usedDefense  >= defense;

  let html = '<div class="mod-slots-row">';
  if (upgrades > 0) html += `<span class="mod-slot-chip${upgFull ? ' full' : ''}">Upgrades: ${usedUpgrades}/${upgrades}</span>`;
  if (defense  > 0) html += `<span class="mod-slot-chip defense${defFull ? ' full' : ''}">Defense: ${usedDefense}/${defense}</span>`;
  if (abilities > 0) html += `<span class="mod-slot-chip ability${abiFull ? ' full' : ''}">Abilities: ${usedAbilities}/${abilities}</span>`;
  html += '</div>';

  // Active modifier rows
  const active = Object.entries(selectedModifiers).filter(([, lv]) => lv > 0);
  if (active.length > 0) {
    html += '<div class="mod-active-list">';
    for (const [key, level] of active) {
      const def = MODIFIER_DEFS[key];
      if (!def) continue;
      const isAbility = def.slot === 'abilities';
      const isDefense = def.slot === 'defense';
      const slotUsed  = isAbility ? usedAbilities : isDefense ? usedDefense : usedUpgrades;
      const slotAvail = isAbility ? abilities : isDefense ? defense : upgrades;
      const canInc = level < def.maxLevel && slotUsed < slotAvail;
      const levelCtrl = def.maxLevel > 1
        ? `<div class="mod-stepper">
             <button class="mod-step-btn" onclick="changeModifier('${key}',-1)">−</button>
             <span class="mod-level">${level}/${def.maxLevel}</span>
             <button class="mod-step-btn" onclick="changeModifier('${key}',1)" ${canInc ? '' : 'disabled'}>+</button>
           </div>`
        : '';
      const tagClass = isAbility ? ' ability' : isDefense ? ' defense' : '';
      const tagLabel = isAbility ? 'abi' : isDefense ? 'def' : 'upg';
      html += `<div class="mod-active-row">
        <span class="mod-slot-tag${tagClass}">${tagLabel}</span>
        <span class="mod-active-name">${def.display}</span>
        ${levelCtrl}
        <button class="mod-remove-btn" onclick="removeModifier('${key}')" title="Remove">×</button>
      </div>`;
    }
    html += '</div>';
  }

  // Add dropdown — only show modifiers not already active
  const bySlot = { upgrades: [], defense: [], abilities: [] };
  for (const [k, d] of Object.entries(MODIFIER_DEFS)) {
    if (selectedModifiers[k] > 0) continue;
    if (bySlot[d.slot]) bySlot[d.slot].push([k, d]);
  }
  for (const arr of Object.values(bySlot)) arr.sort(([, a], [, b]) => a.display.localeCompare(b.display));

  html += '<select class="mod-add-select" onchange="addModifierFromSelect(this)">';
  html += '<option value="">+ Add modifier…</option>';
  if (bySlot.upgrades.length) {
    html += '<optgroup label="── Upgrades ──">';
    for (const [k, d] of bySlot.upgrades)
      html += `<option value="${k}"${upgFull ? ' disabled' : ''}>${d.display}</option>`;
    html += '</optgroup>';
  }
  if (bySlot.defense.length && defense > 0) {
    html += '<optgroup label="── Defense ──">';
    for (const [k, d] of bySlot.defense)
      html += `<option value="${k}"${defFull ? ' disabled' : ''}>${d.display}</option>`;
    html += '</optgroup>';
  }
  if (bySlot.abilities.length) {
    html += '<optgroup label="── Abilities ──">';
    for (const [k, d] of bySlot.abilities)
      html += `<option value="${k}"${abiFull ? ' disabled' : ''}>${d.display}</option>`;
    html += '</optgroup>';
  }
  html += '</select>';

  document.getElementById('modifierPanel').innerHTML = html;
}

function addModifierFromSelect(sel) {
  const key = sel.value;
  sel.value = '';
  if (!key || !MODIFIER_DEFS[key]) return;
  const def  = MODIFIER_DEFS[key];
  const tool = TOOLS[currentTool];
  const avail = tool?.slots?.[def.slot] ?? 0;
  // Count slots already used by other modifiers of the same type
  let used = 0;
  for (const [k, lv] of Object.entries(selectedModifiers)) {
    if (lv && MODIFIER_DEFS[k]?.slot === def.slot) used += lv;
  }
  if (avail > 0 && used >= avail) return; // no room
  selectedModifiers[key] = 1;
  autoSave();
  renderModifiers();
  renderStats();
}

function removeModifier(key) {
  delete selectedModifiers[key];
  autoSave();
  renderModifiers();
  renderStats();
}

function changeModifier(key, delta) {
  const def = MODIFIER_DEFS[key];
  if (!def) return;
  const tool = TOOLS[currentTool];
  const slots = tool?.slots ?? {};
  const avail = slots[def.slot] ?? 0;
  const cur = selectedModifiers[key] ?? 0;
  let next = Math.max(0, Math.min(def.maxLevel, cur + delta));
  // Enforce slot cap when incrementing
  if (delta > 0 && avail > 0) {
    let used = 0;
    for (const [k, lv] of Object.entries(selectedModifiers)) {
      if (!lv || k === key) continue;
      if (MODIFIER_DEFS[k]?.slot === def.slot) used += lv;
    }
    next = Math.min(next, cur + Math.max(0, avail - used - cur));
  }
  selectedModifiers[key] = next;
  if (next === 0) delete selectedModifiers[key];
  autoSave();
  renderModifiers();
  renderStats();
}

// ═══════════════════════════════════════════════════════════════
// SLOT COLUMN OPTIMIZER
// ═══════════════════════════════════════════════════════════════
const collapsedSlotCols = new Set();

function slotScore(mat, statType, goal) {
  const tierVal = mat.head ? (TIERS[mat.head.tier?.split(':')[1]] ?? 0) : 0;
  if (statType === 'head' && mat.head) {
    if (goal === 'mining')     return mat.head.mspd * 40 + tierVal * 30 + mat.head.dur * 0.05;
    if (goal === 'dps')        return mat.head.atk * 15 + mat.head.mspd * 3;
    if (goal === 'damage')     return mat.head.atk * 20;
    if (goal === 'durability') return mat.head.dur;
    return mat.head.atk * 10 + mat.head.mspd * 5 + mat.head.dur * 0.05;
  }
  if (statType === 'handle' && mat.handle)
    return (WIZ_HANDLE_WEIGHTS[goal] ?? WIZ_HANDLE_WEIGHTS.balanced)(mat.handle);
  if (statType === 'grip' && (mat.grip || mat.handle)) {
    const g = mat.grip ?? mat.handle;
    return (WIZ_HANDLE_WEIGHTS[goal] ?? WIZ_HANDLE_WEIGHTS.balanced)(g);
  }
  if (statType === 'limb' && mat.limbDur) return mat.limbDur;
  if (ARMOR_PLATING_TYPES.has(statType) && mat.platings?.[statType]) {
    const p = mat.platings[statType];
    return p.armor * 100 + p.tough * 50 + p.kbRes * 20 + p.dur * 0.03;
  }
  if (statType === 'maille') return 1; // maille only has traits, rank equally
  return 0;
}

function slotStatStr(mat, statType, goal) {
  if (statType === 'head' && mat.head) {
    if (goal === 'mining')                  return `\u26cf ${mat.head.mspd}`;
    if (goal === 'dps' || goal === 'damage') return `\u2694 ${mat.head.atk}`;
    if (goal === 'durability')              return `\u2764 ${mat.head.dur}`;
    return `\u26cf ${mat.head.mspd}`;
  }
  if (statType === 'handle' && mat.handle) {
    const fmtPct = v => `${v >= 0 ? '+' : ''}${(v * 100).toFixed(0)}%`;
    if (goal === 'mining')     return `\u00d7mspd ${fmtPct(mat.handle.mspdMult)}`;
    if (goal === 'durability') return `\u00d7dur ${fmtPct(mat.handle.durMult)}`;
    const dmg = mat.handle.dmg !== 0 ? `atk ${mat.handle.dmg >= 0 ? '+' : ''}${mat.handle.dmg}` : '';
    const spd = mat.handle.spd !== 0 ? `spd ${mat.handle.spd >= 0 ? '+' : ''}${mat.handle.spd}` : '';
    return [dmg, spd].filter(Boolean).join(' ') || `\u00d7dur ${fmtPct(mat.handle.durMult)}`;
  }
  if (statType === 'grip' && (mat.grip || mat.handle)) {
    const g = mat.grip ?? mat.handle;
    const fmtPct = v => `${v >= 0 ? '+' : ''}${(v * 100).toFixed(0)}%`;
    if (goal === 'durability') return `\u00d7dur ${fmtPct(g.durMult)}`;
    return g.dmg !== 0 ? `atk ${g.dmg >= 0 ? '+' : ''}${g.dmg}` : `\u00d7dur ${fmtPct(g.durMult)}`;
  }
  if (statType === 'limb' && mat.limbDur) return `\u2764 ${mat.limbDur}`;
  if (ARMOR_PLATING_TYPES.has(statType) && mat.platings?.[statType]) {
    const p = mat.platings[statType];
    return `\u{1F6E1} ${p.armor}` + (p.tough ? ` tough ${p.tough}` : '');
  }
  return '';
}

/** Compute per-stat max values for a slot's material list, for bar scaling. */
function slotStatMaxes(sorted, statType) {
  const mx = {};
  for (const [, m] of sorted) {
    if ((statType === 'head' || statType === 'limb') && m.head) {
      mx.dur  = Math.max(mx.dur  || 0, m.head.dur);
      mx.atk  = Math.max(mx.atk  || 0, m.head.atk);
      mx.mspd = Math.max(mx.mspd || 0, m.head.mspd);
    } else if (statType === 'limb' && m.limbDur) {
      mx.dur = Math.max(mx.dur || 0, m.limbDur);
    } else if (statType === 'handle' && m.handle) {
      mx.durMult  = Math.max(mx.durMult  || 0, Math.abs(m.handle.durMult));
      mx.dmg      = Math.max(mx.dmg      || 0, Math.abs(m.handle.dmg));
      mx.spd      = Math.max(mx.spd      || 0, Math.abs(m.handle.spd));
      mx.mspdMult = Math.max(mx.mspdMult || 0, Math.abs(m.handle.mspdMult));
    } else if (statType === 'grip' && (m.grip || m.handle)) {
      const g = m.grip ?? m.handle;
      mx.durMult = Math.max(mx.durMult || 0, Math.abs(g.durMult));
      mx.dmg     = Math.max(mx.dmg     || 0, Math.abs(g.dmg));
    } else if (ARMOR_PLATING_TYPES.has(statType) && m.platings?.[statType]) {
      const p = m.platings[statType];
      mx.armor = Math.max(mx.armor || 0, p.armor);
      mx.dur   = Math.max(mx.dur   || 0, p.dur);
      mx.tough = Math.max(mx.tough || 0, p.tough);
      mx.kbRes = Math.max(mx.kbRes || 0, p.kbRes);
    }
  }
  return mx;
}

/** Render stat bars for a material row in an optimizer slot column. */
function slotStatBars(mat, statType, maxes) {
  const bar = (key, val, max, fmt) => {
    if (max === 0) return '';
    const pct = Math.max(0, Math.min(100, Math.abs(val) / max * 100)).toFixed(1);
    const sign = val < 0 ? '−' : (val > 0 && key !== 'dur' && key !== 'mspd' && key !== 'armor' && key !== 'tough' && key !== 'kbRes' ? '+' : '');
    const dispVal = fmt ? fmt(val) : (sign + val);
    return `<div class="slot-stat-bar">
      <span class="ssb-key">${key}</span>
      <div class="ssb-track"><div class="ssb-fill" style="width:${pct}%"></div></div>
      <span class="ssb-val">${dispVal}</span>
    </div>`;
  };
  const pct = v => `${v >= 0 ? '+' : ''}${(v * 100).toFixed(0)}%`;
  const parts = [];
  if ((statType === 'head' || statType === 'limb') && mat.head) {
    parts.push(bar('dur',  mat.head.dur,  maxes.dur  || 1, null));
    parts.push(bar('atk',  mat.head.atk,  maxes.atk  || 1, null));
    parts.push(bar('mspd', mat.head.mspd, maxes.mspd || 1, null));
  } else if (statType === 'limb' && mat.limbDur) {
    parts.push(bar('dur', mat.limbDur, maxes.dur || 1, null));
  } else if (statType === 'handle' && mat.handle) {
    parts.push(bar('dur×',  mat.handle.durMult,  maxes.durMult  || 1, pct));
    if (maxes.dmg)      parts.push(bar('atk+',  mat.handle.dmg,      maxes.dmg      || 1, pct));
    if (maxes.spd)      parts.push(bar('spd+',  mat.handle.spd,      maxes.spd      || 1, pct));
    if (maxes.mspdMult) parts.push(bar('mspd×', mat.handle.mspdMult, maxes.mspdMult || 1, pct));
  } else if (statType === 'grip' && (mat.grip || mat.handle)) {
    const g = mat.grip ?? mat.handle;
    parts.push(bar('dur×', g.durMult, maxes.durMult || 1, pct));
    if (maxes.dmg) parts.push(bar('atk+', g.dmg, maxes.dmg || 1, pct));
  } else if (ARMOR_PLATING_TYPES.has(statType) && mat.platings?.[statType]) {
    const p = mat.platings[statType];
    parts.push(bar('armor', p.armor, maxes.armor || 1, null));
    parts.push(bar('dur',   p.dur,   maxes.dur   || 1, null));
    if (maxes.tough) parts.push(bar('tough', p.tough, maxes.tough || 1, null));
    if (maxes.kbRes) parts.push(bar('kbres', p.kbRes, maxes.kbRes || 1, null));
  }
  if (!parts.length) return '';
  return `<div class="slot-mat-stats">${parts.join('')}</div>`;
}

function toggleSlotCol(partIdx) {
  if (collapsedSlotCols.has(partIdx)) collapsedSlotCols.delete(partIdx);
  else collapsedSlotCols.add(partIdx);
  renderOptimizerSlots();
}

function renderOptimizerSlots() {
  const el = document.getElementById('slotColumns');
  if (!el) return;
  if (TOOLS[currentTool]?.fixedStats) {
    el.innerHTML = '<div class="empty-msg" style="padding:18px 0">Staves have fixed stats — all stats are determined by which staff you choose, not by material parts.</div>';
    return;
  }
  const goal         = document.getElementById('optGoal')?.value ?? 'balanced';
  const maxTier      = +(document.getElementById('optMaxTier')?.value ?? 4);
  const forceFortune = document.getElementById('forceFortune')?.checked ?? false;
  const tool         = TOOLS[currentTool];
  const isMeleeHarvestTool = tool.parts.some(p => p.statType === 'head');

  el.innerHTML = tool.parts.map((part, i) => {
    const collapsed = collapsedSlotCols.has(i);
    const curVal    = selectedMaterials[i] ?? '';
    const curMat    = MATERIALS[curVal];

    if (collapsed) {
      return `<div class="slot-col collapsed">
        <div class="slot-col-header" onclick="toggleSlotCol(${i})" title="${escHtml(part.label)}: ${escHtml(curMat?.display ?? '\u2014')}">
          <span class="slot-col-name">${escHtml(part.label)}</span>
          <button class="slot-col-toggle">+</button>
        </div>
      </div>`;
    }

    let opts;
    if (forceFortune && isMeleeHarvestTool && part.statType === 'binding') {
      const ah = MATERIALS['ancient_hide'] ?? CONDITIONAL_MATERIALS['ancient_hide'];
      opts = ah ? [['ancient_hide', ah]] : materialOptions(part.statType, maxTier);
    } else {
      opts = materialOptions(part.statType, maxTier);
    }

    const sorted = [...opts].sort(([, a], [, b]) => slotScore(b, part.statType, goal) - slotScore(a, part.statType, goal));
    const maxes  = slotStatMaxes(sorted, part.statType);

    // Count how many OTHER slots already use each material key so trait levels
    // can be shown at their stacked value (base_level × total_parts_using_mat).
    const otherMatCount = {};
    for (let j = 0; j < tool.parts.length; j++) {
      if (j === i) continue;
      const mk = selectedMaterials[j] ?? '';
      if (mk) otherMatCount[mk] = (otherMatCount[mk] || 0) + 1;
    }

    const rows = sorted.map(([k, m]) => {
      const isSel     = k === curVal;
      const tierKey   = m.head?.tier?.split(':')[1] ?? '';
      const tierBadge = (() => { const t = m.head?.tier; const icon = t && TIER_ICON[t]; return icon ? `<img src="${icon}" alt="${TIER_LABEL[t]??tierKey}" class="slot-mat-tier-icon" title="${TIER_LABEL[t]??tierKey} Tier">` : tierKey ? `<span class="slot-mat-tier t-${tierKey}">${TIER_ABBREV[t] ?? tierKey[0].toUpperCase()}</span>` : ''; })();
      const otherCount = otherMatCount[k] ?? 0;
      const traitPill = (t, cls) => {
        const lvl    = (t.level ?? 1) * (1 + otherCount);
        const sname  = stackedTraitName(t.name, lvl);
        const valStr = traitValueStr(t.id, lvl);
        const label  = sname + (valStr ? ' (' + valStr + ')' : '');
        return `<span class="slot-mat-row-trait${cls ? ' ' + cls : ''}"
          data-tid="${escHtml(t.id)}" data-tlvl="${lvl}"
          data-tname="${escHtml(sname)}" data-tdesc="${escHtml(t.desc ?? '')}"
          onmouseenter="showTraitTip(event,this)" onmouseleave="hideTraitTip()"
          >${escHtml(label)}</span>`;
      };
      const allTraits = [
        ...(m.traits ?? []).map(t => traitPill(t, '')),
        ...(isMeleeHarvestTool && m.perStatTraits?.melee_harvest
            ? m.perStatTraits.melee_harvest.map(t => traitPill(t, 'perstat'))
            : []),
      ].join('');
      const statBarsHtml = slotStatBars(m, part.statType, maxes);
      const isHidden = MAT_TO_MOD[k] === 'tc3_hidden';
      const hiddenBadge = isHidden ? '<span class="mat-drop-only" title="Drop-only — not craftable">drop-only</span>' : '';
      return `<div class="slot-mat-row${isSel ? ' selected' : ''}${isHidden ? ' non-craftable' : ''}" onclick="selectMaterial(${i},'${escHtml(k)}');renderOptimizerSlots()">
        <div class="slot-mat-row-top">
          <span class="slot-mat-row-name">${escHtml(m.display)}</span>
          ${hiddenBadge}${tierBadge}
        </div>
        ${statBarsHtml}
        ${allTraits ? `<div class="slot-mat-row-traits">${allTraits}</div>` : ''}
      </div>`;
    }).join('');

    return `<div class="slot-col">
      <div class="slot-col-header">
        <span class="slot-col-name">${escHtml(part.label)}</span>
        <span class="slot-col-cur">${escHtml(curMat?.display ?? '')}</span>
        <button class="slot-col-toggle" onclick="toggleSlotCol(${i})">&#x2212;</button>
      </div>
      <div class="slot-col-body">${rows}</div>
    </div>`;
  }).join('');
}

function renderAll() {
  renderToolTabs();
  renderPartSlots();
  renderStats();
  renderToolInfo();
  renderModifiers();
  renderOptimizerSlots();
}

// ═══════════════════════════════════════════════════════════════
// SAVE / LOAD
// ═══════════════════════════════════════════════════════════════
const LS_STATE        = 'tc3opt_state';
const LS_INTEGRATIONS = 'tc3opt_integrations';
// Defaults match CABIN 2.1.3's mod list (Thermal + common metals);
// once the user touches the Mods panel their choice is persisted.
let   ENABLED_INTEGRATIONS = new Set(
  JSON.parse(localStorage.getItem(LS_INTEGRATIONS) ?? 'null')
  ?? (DATA?.cabin?.defaultIntegrations ?? [])
);
const HAS_SAVED_INTEGRATIONS = localStorage.getItem(LS_INTEGRATIONS) != null;
const LS_BUILDS = 'tc3opt_builds';

function escHtml(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

// Silently persist current tool + materials + modifiers across page reloads
function autoSave() {
  try {
    localStorage.setItem(LS_STATE, JSON.stringify({
      tool: currentTool,
      mats: { ...selectedMaterials },
      mods: { ...selectedModifiers },
    }));
  } catch {}
}

// Restore the last auto-saved state; returns true if successful
function autoLoad() {
  try {
    const saved = JSON.parse(localStorage.getItem(LS_STATE) ?? 'null');
    if (!saved || !TOOLS[saved.tool]) return false;
    currentTool  = saved.tool;
    currentGroup = TOOLS[currentTool]?.group ?? '';
    selectedMaterials = {};
    const savedTool = TOOLS[currentTool];
    savedTool.parts.forEach((part, i) => {
      const k = saved.mats?.[i];
      const valid = k && MATERIALS[k] && materialOptions(part.statType).some(([mk]) => mk === k);
      selectedMaterials[i] = valid ? k : pickDefaultMat(savedTool, i, part.statType);
    });
    selectedModifiers = {};
    for (const [key, level] of Object.entries(saved.mods ?? {})) {
      if (MODIFIER_DEFS[key] && typeof level === 'number') selectedModifiers[key] = level;
    }
    return true;
  } catch { return false; }
}

function getBuilds() {
  try { return JSON.parse(localStorage.getItem(LS_BUILDS) ?? '[]'); } catch { return []; }
}

function saveNamedBuild() {
  const nameEl = document.getElementById('buildName');
  const name   = nameEl.value.trim();
  if (!name) { nameEl.focus(); return; }
  const builds = getBuilds();
  const tool   = TOOLS[currentTool];
  // Material names for subtitle
  const matNames = tool.parts.map((_, i) => MATERIALS[selectedMaterials[i]]?.display ?? '').filter(Boolean).join(' / ');
  builds.push({
    id: Date.now().toString(), name,
    tool: currentTool, toolDisplay: tool.display, icon: tool.icon,
    matNames, mats: { ...selectedMaterials }, mods: { ...selectedModifiers },
    savedAt: new Date().toISOString(),
  });
  try {
    localStorage.setItem(LS_BUILDS, JSON.stringify(builds));
    nameEl.value = '';
    renderBuilds();
  } catch {}
}

function loadNamedBuild(id) {
  const build = getBuilds().find(b => b.id === id);
  if (!build || !TOOLS[build.tool]) return;
  currentTool = build.tool;
  selectedMaterials = {};
  const buildTool = TOOLS[currentTool];
  buildTool.parts.forEach((part, i) => {
    const k = build.mats?.[i];
    const valid = k && MATERIALS[k] && materialOptions(part.statType).some(([mk]) => mk === k);
    selectedMaterials[i] = valid ? k : pickDefaultMat(buildTool, i, part.statType);
  });
  selectedModifiers = {};
  for (const [key, level] of Object.entries(build.mods ?? {})) {
    if (MODIFIER_DEFS[key] && typeof level === 'number') selectedModifiers[key] = level;
  }
  autoSave();
  renderAll();

}

function deleteNamedBuild(id) {
  const builds = getBuilds().filter(b => b.id !== id);
  try { localStorage.setItem(LS_BUILDS, JSON.stringify(builds)); renderBuilds(); } catch {}
}

function renderBuilds() {
  const builds = getBuilds();
  const el = document.getElementById('buildList');
  if (!builds.length) {
    el.innerHTML = '<div class="build-empty">No saved builds yet.</div>';
    return;
  }
  el.innerHTML = builds.slice().reverse().map(b => `
    <div class="build-item">
      <div class="build-item-info">
        <div class="build-item-name">${escHtml(b.name)}</div>
        <div class="build-item-tool">${escHtml(b.icon ?? '')} ${escHtml(b.toolDisplay ?? b.tool)} · ${escHtml(b.matNames ?? '')}</div>
      </div>
      <button class="build-btn" onclick="loadNamedBuild('${b.id}')">Load</button>
      <button class="build-btn del" onclick="deleteNamedBuild('${b.id}')">✕</button>
    </div>`).join('');
}

// ═══════════════════════════════════════════════════════════════
// EVENTS
// ═══════════════════════════════════════════════════════════════
function selectTool(key) {
  currentTool       = key;
  currentGroup      = TOOLS[key]?.group ?? currentGroup;
  selectedMaterials = {};
  selectedModifiers = {};
  const tool = TOOLS[key];
  tool.parts.forEach((part, i) => {
    selectedMaterials[i] = pickDefaultMat(tool, i, part.statType);
  });
  const goal = TOOL_DEFAULT_GOAL[key] ?? 'balanced';
  document.getElementById('optGoal').value = goal;
  autoSave();
  renderAll();
}

function selectMaterial(idx, val) {
  selectedMaterials[idx] = val;
  autoSave();
  renderStats();
}

// ═══════════════════════════════════════════════════════════════
// OPTIMIZER
// ═══════════════════════════════════════════════════════════════
function runOptimizer() {
  const goal         = document.getElementById('optGoal').value;
  const maxTier      = +document.getElementById('optMaxTier').value;
  const forceFortune = document.getElementById('forceFortune')?.checked ?? false;
  const tool         = TOOLS[currentTool];
  // ancient_hide can only provide fortune if this tool is a melee_harvest type
  const toolHasHead  = tool.parts.some(p => p.statType === 'head');

  // Step 1: Get raw options per slot, then prune dominated materials
  const rawOpts    = tool.parts.map(p => materialOptions(p.statType, maxTier));
  const prunedOpts = rawOpts.map((opts, i) => {
    const st = tool.parts[i].statType;
    // Force Fortune: lock binding slots to ancient_hide (tier-filter bypass included)
    if (forceFortune && toolHasHead && st === 'binding') {
      const ah = MATERIALS['ancient_hide'] ?? CONDITIONAL_MATERIALS['ancient_hide'];
      if (ah) return [['ancient_hide', ah]];
    }
    // Binding/bowstring/grip contribute no stats — fix to current selection to avoid
    // duplicate results that differ only in trait-slot material (stats would be identical)
    if (st === 'binding' || st === 'bowstring' || st === 'grip') {
      const cur = selectedMaterials[i];
      const hit = opts.find(([k]) => k === cur);
      return hit ? [hit] : opts.slice(0, 1);
    }
    return pruneSlot(st, opts);
  });

  const partKeys   = prunedOpts.map(opts => opts.map(([k]) => k));
  const prunedMats = rawOpts.reduce((s, o, i) => s + o.length - prunedOpts[i].length, 0);

  function* product(arrays) {
    if (!arrays.length) { yield []; return; }
    for (const h of arrays[0])
      for (const rest of product(arrays.slice(1)))
        yield [h, ...rest];
  }

  // Step 2: Compute stats for all pruned combos
  const results = [];
  for (const combo of product(partKeys)) {
    const stats = calcStats(currentTool, combo);
    results.push({ combo, stats });
  }

  // Step 3: Pareto filter — drop combos dominated on ALL of dur/atk/atkSpd/mspd/tier
  const pareto = paretoFilter(results);
  pareto.forEach(r => { r.score = scoreStats(r.stats, goal); });
  pareto.sort((a, b) => b.score - a.score);
  const top = pareto.slice(0, 10);

  const goalLabels = { dps:'DPS', damage:'Attack', durability:'Durability', mining:'Mining', balanced:'Balanced' };

  document.getElementById('optResults').innerHTML = `
    <div style="margin-bottom:10px;font-size:12px;color:var(--muted);line-height:1.9">
      Pruned <strong style="color:var(--text)">${prunedMats}</strong> dominated slot choices ·
      evaluated <strong style="color:var(--text)">${results.length.toLocaleString()}</strong> combinations ·
      <strong style="color:var(--accent2)">${pareto.length}</strong> Pareto-optimal ·
      ranked by <strong style="color:var(--accent)">${goalLabels[goal]}</strong> · max tier ${maxTier}
    </div>
    <div class="opt-results">
      ${top.map((r, idx) => {
        const tierCls = TIER_CLASS[r.stats.tier] ?? '';

        // Build per-material breakdown rows
        const partRows = r.combo.map((matKey, pi) => {
          const part = tool.parts[pi];
          const mat  = MATERIALS[matKey];
          if (!mat) return '';

          // Stat contribution summary for this slot
          const contrib = [];
          const st = part.statType;
          if (st === 'head' && mat.head) {
            const tierName = TIER_LABEL[mat.head.tier] ?? mat.head.tier.split(':')[1];
            contrib.push(`⛏ ${mat.head.mspd}`);
            contrib.push(tierName);
            contrib.push(`❤ ${mat.head.dur}`);
            contrib.push(`⚔ ${mat.head.atk}`);
          } else if ((st === 'handle' || st === 'grip') && mat.handle) {
            const fmtPct = v => `${v >= 0 ? '+' : ''}${(v * 100).toFixed(0)}%`;
            const fmtVal = v => `${v >= 0 ? '+' : ''}${v}`;
            if (mat.handle.durMult  !== 0) contrib.push(`×dur ${fmtPct(mat.handle.durMult)}`);
            if (mat.handle.mspdMult !== 0) contrib.push(`×mspd ${fmtPct(mat.handle.mspdMult)}`);
            if (mat.handle.dmg      !== 0) contrib.push(`atk ${fmtVal(mat.handle.dmg)}`);
            if (mat.handle.spd      !== 0) contrib.push(`spd ${fmtVal(mat.handle.spd)}`);
            if (!contrib.length) contrib.push('no stat bonus');
          } else if (st === 'limb' && mat.limbDur) {
            contrib.push(`❤ ${mat.limbDur}`);
          } else {
            contrib.push('traits only');
          }

          // Trait chips for this specific material
          const matTraitChips = r.stats.traits
            .filter(t => t.material === mat.display)
            .map(t => {
              const tip = `<span class="opt-trait-tip">
                <span class="ott-name">${escHtml(t.name)}</span>
                <span class="ott-src">from ${escHtml(t.material ?? '')}</span>
                ${t.desc ? `<span class="ott-desc">${escHtml(t.desc)}</span>` : ''}
              </span>`;
              return `<span class="opt-trait-chip">${escHtml(t.name)}${tip}</span>`;
            }).join('');

          return `<div class="opt-mat-row">
            <span class="opt-mat-slot">${escHtml(part.label)}</span>
            <div class="opt-mat-right">
              <div class="opt-mat-header">
                <span class="opt-mat-name">${escHtml(mat.display)}</span>
                <span class="opt-mat-contrib">${contrib.join(' · ')}</span>
              </div>
              ${matTraitChips ? `<div class="opt-mat-traits-inline">${matTraitChips}</div>` : ''}
            </div>
          </div>`;
        }).join('');

        return `<div class="opt-result">
          <div class="opt-rank rank-${idx+1}">${idx+1}</div>
          <div>
            <div class="opt-stats-row">
              <span class="opt-stat-chip">❤ <span class="val">${r.stats.dur.toLocaleString()}</span></span>
              <span class="opt-stat-chip">⚔ <span class="val">${r.stats.dps}</span> DPS</span>
              <span class="opt-stat-chip">⛏ <span class="val">${r.stats.mspd}</span></span>
              ${(() => { const ti = r.stats.tier; const icon = TIER_ICON[ti]; return icon ? `<img src="${icon}" alt="${TIER_LABEL[ti]??ti}" class="tier-icon" title="${TIER_LABEL[ti]??ti} Tier" style="width:14px;height:14px">` : `<span class="tier-badge ${tierCls}" style="font-size:10px;padding:1px 7px;margin-top:0">${TIER_LABEL[ti]}</span>`; })()}
            </div>
            <div class="opt-mat-list">${partRows}</div>
          </div>
          <button class="opt-apply-btn" onclick="applyCombo(${escHtml(JSON.stringify(r.combo))})">Apply →</button>
        </div>`;
      }).join('')}
    </div>`;
}

function applyCombo(combo) {
  TOOLS[currentTool].parts.forEach((_, i) => { selectedMaterials[i] = combo[i]; });
  renderPartSlots();
  renderStats();
}

// ─── Goal/handle weights (used by slotScore) ─────────────────
const WIZ_GOAL_WEIGHTS = {
  mining:     (h) => (h ? h.mspd * 10 : 0),
  damage:     (h) => (h ? h.atk * 20 : 0),
  durability: (h) => (h ? h.dur * 0.1 : 0),
  dps:        (h) => (h ? h.atk * 15 + h.mspd * 3 : 0),
  balanced:   (h) => (h ? h.atk * 10 + h.mspd * 5 + h.dur * 0.05 : 0),
  defense:    (h) => 0, // armor tools have no head slot
};

const WIZ_HANDLE_WEIGHTS = {
  mining:     (h) => h.mspdMult * 30 + h.durMult * 5,
  damage:     (h) => h.dmg * 30 + h.durMult * 5,
  durability: (h) => h.durMult * 40,
  dps:        (h) => h.dmg * 20 + h.spd * 20 + h.durMult * 5,
  balanced:   (h) => h.dmg * 10 + h.spd * 8 + h.durMult * 12 + h.mspdMult * 10,
  defense:    (h) => h.durMult * 20, // armor: prioritize durability
};

// ═══════════════════════════════════════════════════════════════
// INTEGRATIONS PANEL
// ═══════════════════════════════════════════════════════════════
function openIntegrations() {
  document.getElementById('intOverlay').style.display = 'flex';
  renderIntegrations();
}
function closeIntegrations() {
  document.getElementById('intOverlay').style.display = 'none';
}
function toggleIntegration(modKey) {
  if (ENABLED_INTEGRATIONS.has(modKey)) {
    ENABLED_INTEGRATIONS.delete(modKey);
    for (const name of MOD_INTEGRATIONS[modKey].materials) delete MATERIALS[name];
  } else {
    ENABLED_INTEGRATIONS.add(modKey);
    for (const name of MOD_INTEGRATIONS[modKey].materials) {
      if (CONDITIONAL_MATERIALS[name]) MATERIALS[name] = CONDITIONAL_MATERIALS[name];
    }
  }
  localStorage.setItem(LS_INTEGRATIONS, JSON.stringify([...ENABLED_INTEGRATIONS]));
  renderIntegrations();
  renderPartSlots();
  renderStats();
}
function renderIntegrations() {
  const rows = Object.entries(MOD_INTEGRATIONS).map(([key, mod]) => {
    const enabled = ENABLED_INTEGRATIONS.has(key);
    const presentCount = mod.materials.filter(n => CONDITIONAL_MATERIALS[n]).length;
    const mats = mod.materials
      .filter(n => CONDITIONAL_MATERIALS[n])
      .map(n => CONDITIONAL_MATERIALS[n].display ?? n)
      .join(', ');
    if (!presentCount) return ''; // no stats data loaded for this group
    return `
      <label class="int-row ${enabled ? 'int-enabled' : ''}">
        <input type="checkbox" ${enabled ? 'checked' : ''} onchange="toggleIntegration('${key}')">
        <div class="int-info">
          <span class="int-label">${mod.label}</span>
          <span class="int-mats">${mats}</span>
        </div>
      </label>`;
  }).join('');
  document.getElementById('intList').innerHTML = rows || '<div style="color:var(--muted);font-size:13px">No integration data loaded.</div>';
}

// ═══════════════════════════════════════════════════════════════
// TRAIT TOOLTIP
// ═══════════════════════════════════════════════════════════════
function showTraitTip(e, el) {
  const tip    = document.getElementById('traitTooltip');
  const id     = el.dataset.tid;
  const lvl    = +el.dataset.tlvl;
  const sname  = el.dataset.tname;
  const langDesc = el.dataset.tdesc;
  const valStr   = traitValueStr(id, lvl);
  const detailDesc = TRAIT_KNOWN[id]?.desc ?? langDesc;

  let html = `<div class="tt-name">${escHtml(sname)}</div>`;
  if (valStr) html += `<div class="tt-val">${escHtml(valStr)}</div>`;
  if (detailDesc) html += `<div class="tt-desc">${escHtml(detailDesc)}</div>`;

  tip.innerHTML = html;
  tip.style.display = 'block';
  _positionTip(e, tip);
}

function hideTraitTip() {
  document.getElementById('traitTooltip').style.display = 'none';
}

function _positionTip(e, tip) {
  const pad = 10;
  tip.style.left = '0'; tip.style.top = '0'; // reset so getBoundingClientRect is valid
  const tw = tip.offsetWidth, th = tip.offsetHeight;
  let x = e.clientX + pad, y = e.clientY + pad;
  if (x + tw > window.innerWidth  - pad) x = e.clientX - tw - pad;
  if (y + th > window.innerHeight - pad) y = e.clientY - th - pad;
  tip.style.left = x + 'px';
  tip.style.top  = y + 'px';
}

// ── Start ─────────────────────────────────────────────────────
init();
